### PR TITLE
chore(Storybook): update to latest

### PR DESCRIPTION
**Pull request by tujoworker**

### CODE REVIEW

**Review by langz — APPROVED** [review]
📖

**Comment by tujoworker** [comment]
Looks like there is an deps lock file audit issue. It did work fine with Yarn v4 when I tested i locally. So this PR relies on #2825 in order to run properly.

**Comment by langz** [comment]
> Looks like there is an deps lock file audit issue. It did work fine with Yarn v4 when I tested i locally. So this PR relies on #2825 in order to run properly.

Thanks for following-up on this, I saw the build failing after I had approved 🏎️ 🏁

**Pull request merged**
