### PR TITLE
fix(InputMasked): fix integerLimit to work during typing

### PR DESCRIPTION
**Pull request by tujoworker**
Here is [reprod](https://codesandbox.io/s/eufemia-starter-forked-tnozky?file=/src/App.tsx:108-559) of the bug.

### CODE REVIEW

**Review by langz — APPROVED** [review]
👍

**Comment by jorgenholme** [comment]
It looks like the limit stops at 8 integers even though the limit is set to 10. Is it counting the spaces maybe?
image

**Comment by tujoworker** [comment]
yes, good point. Will fix that 👍

**Comment by tujoworker** [comment]
@jorgenholme Can you check if the latest changes work as expected? [Here](https://github.com/dnbexperience/eufemia/compare/9ac75fb1dfabb9c2cc67ac456f5ac0ef7e9f444c..8993e194324c39ab85fa610213cad58565e50f45) are the changes.

**Review by jorgenholme — APPROVED** [review]

**Comment by jorgenholme** [comment]
Looks great 💯

**Pull request merged**
