### PR TITLE
chore: adds Indeterminate to list of base fields components

### PR DESCRIPTION
**Pull request by langz**

### CODE REVIEW

**Comment by tujoworker** [comment]
Indeterminate is very rarely used. So I don't like the idea that it is listed by default. 
Option can never be used alone, so it is also not that important to have listed in "this" list.

**Comment by tujoworker** [comment]
Yes, there we can/should list them.

**Comment by langz** [comment]
> Yes, there we can/should list them.

Good, I've now set `componentType: 'base-toggle'` for Indeterminate, so that it's included in the list of base fields components(`ListBaseFieldComponents`).

**Review by tujoworker — APPROVED** [review]

**Pull request merged**
