### PR TITLE
chore(Timeline): fix randomly failing test

### PR DESCRIPTION
**Pull request by langz**
I'll try to run the "Verify tests and types" action a few times, to see if I'm able to reproduce the following error/failing test https://github.com/dnbexperience/eufemia/actions/runs/4487837629

### CODE REVIEW

**Comment by tujoworker** [comment]
I tried to find relevant info, and found [this](https://github.com/testing-library/react-testing-library/issues/1159), which is a good read. It just shows that others experience similar "mysterious things".

**Comment by langz** [comment]
> I tried to find relevant info, and found [this](https://github.com/testing-library/react-testing-library/issues/1159), which is a good read. It just shows that others experience similar "mysterious things".

Thanks, I'll give it a read 📖

**Comment by langz** [comment]
I've tried running the "Verify tests and types" action 5-6 times now, without any luck(failing tests).
So maybe this fixed it? I have no idea 😅

**Comment by tujoworker** [comment]
I have experienced the issue a lot the day we have looked into it, but not lastly anymore.

**Comment by langz** [comment]
> I have experienced the issue a lot the day we have looked into it, but not lastly anymore.

Yeah, nekter have I🤣🤔

**Review by tujoworker — APPROVED** [review]
Lets get this in. It does not harm either, even if it would not fix the original issue.

**Pull request merged**
