### PR TITLE
fix(Dropdown): align tertiary dropdown triangle icon with button

### PR DESCRIPTION
**Pull request by joakbjerk**
Proposal on how to solve the alignment issue

Before:
image-2024-09-26-10-09-57-403

After:
Screenshot 2024-09-30 at 12 32 34

Screenshot 2024-09-30 at 12 32 27

### CODE REVIEW

**Review by langz — APPROVED** [review]
Looks good to me 👍 
A shame that we can't  access dropdown-padding-horizontal, is there some other way of making use of this variable? 🤔

**Comment by langz** [comment]
Does it make sense to have a screenshot test for these scenarios, to see if the different variations of arrows align up correctly?

**Comment by joakbjerk** [comment]
> Does it make sense to have a screenshot test for these scenarios, to see if the different variations of arrows align up correctly?

Sounds like that could be handy 🤔

**Comment by joakbjerk** [comment]
> Looks good to me 👍 A shame that we can't access dropdown-padding-horizontal, is there some other way of making use of this variable? 🤔

The only way I can think of is making it global through `:root` but, then it would loose the dropdown scope

**Pull request merged**
