### PR TITLE
release of v10.52

### PR DESCRIPTION
**Pull request by langz**

### CODE REVIEW

**Review by tujoworker — APPROVED** [review]
We should fill inn all the features via this #4081 PR before merge.

**Comment by langz** [comment]
> We should fill inn all the features via this #4081 PR before merge.

Sure, let us do so :)

I'll go for lunch now, but can do it when I come back.

**Comment by tujoworker** [comment]
Not everything needs to be mentioned. I think only features and important things are worth mentioning.

**Pull request merged**
