### PR TITLE
feat(Email): trim value

### LINKED ISSUE #3165: feat(forms): Trim input field value for whitespaces

### PR DESCRIPTION
**Pull request by tujoworker**
Fixes #3165

### CODE REVIEW

**Review by joakbjerk — COMMENTED** [review]
I might be testing this wrong, but the trim does not seem to affect the value displayed inside the `Field.Email` as it does with `Field.String`. The `onChange` value seems to be correct though 🤔


https://github.com/dnbexperience/eufemia/assets/25927156/90a6badf-ff69-4a08-ba32-5d5417b28c8a

**Comment by tujoworker** [comment]
Yeah, `type="email"` does wired things there. No whitespace is added. So the browser actually does that for us. And add a test for that too (if JSDom does it).

I will rename this PR, as there are other relevant changes.

**Review by joakbjerk — APPROVED** [review]
Other than the video I uploaded, looks good 🙏

**Pull request merged**
