### PR TITLE
fix(forms): enhance `Field.Name` validation rule

### PR DESCRIPTION
**Pull request by tujoworker**

### CODE REVIEW

**Review by langz — APPROVED** [review]
Looks fine to me 👍 

I don't 100% understand the validation rule, or why we want/need validation rules for names. Does it exist a rule for how a name could look like? Is it the government who decides this? Is it different from country to country? Or perhaps its DNB who wants these rules for names? 🤔

**Comment by tujoworker** [comment]
We had a very weak check. The new regex is still not very strict, but as you can see in the tests, it takes care of obvious wrongly written names.
I don't think there is the perfect validation for names. But I think this brings us a long way. And yes, the change is made from feedback by the Trident team. That said, they used a much stricter regex.

**Comment by langz** [comment]
> We had a very weak check. The new regex is still not very strict, but as you can see in the tests, it takes care of obvious wrongly written names.
> 
> I don't think there is the perfect validation for names. But I think this brings us a long way. And yes, the change is made from feedback by the Trident team. That said, they used a much stricter regex. 

Thanks for the explanation🫡

**Pull request merged**
