### PR TITLE
feat(Upload): adds property `displayFileExtensionText` to hide file extension text

### PR DESCRIPTION
**Pull request by langz**

### CODE REVIEW

**Comment by joakbjerk** [comment]
Should the .png after the filename be hidden in this screenshot with `displayFileExtensionText` set to `false`, or am I misunderstanding, or looking at the wrong place? 😄 
Screenshot 2024-10-20 at 09 38 30

**Comment by langz** [comment]
> Should the .png after the filename be hidden in this screenshot with `displayFileExtensionText` set to `false`, or am I misunderstanding, or looking at the wrong place? 😄 
> 
> Screenshot 2024-10-20 at 09 38 30
> 
> 

It's this file extension text that will not be displayed:

image

Could of course be both?
Or maybe the naming of the prop or the docs of the prop could be better?

**Comment by joakbjerk** [comment]
> > Should the .png after the filename be hidden in this screenshot with `displayFileExtensionText` set to `false`, or am I misunderstanding, or looking at the wrong place? 😄
> > Screenshot 2024-10-20 at 09 38 30
> 
> It's this file extension text that will not be displayed:
> 
> image
> 
> Could of course be both? Or maybe the naming of the prop or the docs of the prop could be better?

Hmm, not sure how to improve the text, it makes sense when you made me aware that the file extensions are shown in the list, I just didn't know that before 😄

**Review by joakbjerk — APPROVED** [review]

**Comment by langz** [comment]
> > > Should the .png after the filename be hidden in this screenshot with `displayFileExtensionText` set to `false`, or am I misunderstanding, or looking at the wrong place? 😄
> 
> > > Screenshot 2024-10-20 at 09 38 30
> 
> > 
> 
> > It's this file extension text that will not be displayed:
> 
> > 
> 
> > image
> 
> > 
> 
> > Could of course be both? Or maybe the naming of the prop or the docs of the prop could be better?
> 
> 
> 
> Hmm, not sure how to improve the text, it makes sense when you made me aware that the file extensions are shown in the list, I just didn't know about that 😄

I'll try to improve it🤞

**Comment by langz** [comment]
Turns out we don't need this now 🙏

**Pull request closed without merging**
