### PR TITLE
fix(forms): ensure `Section.EditContainer` cancel restores data when path is given

### LINKED ISSUE #3797: Form.Section.EditContainer validation issues
## 🐛 Bug Report

`Form.Section.EditContainer` validation does not always work.

I have come across two issues which is shown in this reproduction:
- When the edit container is opened and the user attempts to finish without doing any changes, leaving the required fields blank, the user is allowed to do so. Attempting to go to the next page will trigger validation, and force the user to fill in the required fields.
- Cancelling editing after having removed text in a required field is allowed by the container, and the blank field is stored. Again, trying to progress in the form will trigger a validation error. Going by this reproduction, this only happens on nested paths.

https://github.com/user-attachments/assets/1e7b05fb-9c41-4aa3-ae63-12c3e82bc936

## To Reproduce

In this reproduction step 1 will demonstrate no validation on cancel and step 2 will have working cancel.
In step 1 the containers are within a `Form.Section` with a set `path`, while in step 2 they are within a `Form.Section` with no path.

https://codesandbox.io/p/sandbox/nested-section-validation-issue-6mrxmv?file=%2Fsrc%2FApp.tsx%3A50%2C9

## Expected behavior

I expect validation to be triggered when finishing changes, even if the user has made no changes.
I expect cancelling to restore the data that was stored when the user opened the section for editing. 

## Eufemia Version

10.42.0

### PR DESCRIPTION
**Pull request by tujoworker**
Fixes #3797

### CODE REVIEW

**Review by langz — APPROVED** [review]
Great, thanks 👍 

I've forked the [CSB](https://codesandbox.io/p/sandbox/nested-section-validation-issue-6mrxmv?file=%2Fsrc%2FApp.tsx%3A50%2C9) from the [issue](https://github.com/dnbexperience/eufemia/issues/3797) @andlbrei reported, and made a new [CSB using this fix](https://codesandbox.io/p/sandbox/nested-section-validation-issue-forked-55wqd3?file=%2Fpackage.json%3A17%2C92) that can be used to validate if the fixes work as expected or not 👍

**Review by langz — COMMENTED** [review]
Great, thanks 👍 

I've forked the [CSB](https://codesandbox.io/p/sandbox/nested-section-validation-issue-6mrxmv?file=%2Fsrc%2FApp.tsx%3A50%2C9) from the [issue](https://github.com/dnbexperience/eufemia/issues/3797) @andlbrei reported, and made a new [CSB using this fix](https://codesandbox.io/p/sandbox/nested-section-validation-issue-forked-55wqd3?file=%2Fpackage.json%3A17%2C92) that can be used to validate if the fixes work as expected or not 👍 


I might not understand the problem entirely, as I felt like I experienced the same issue in the [CSB using this fix](https://codesandbox.io/p/sandbox/nested-section-validation-issue-forked-55wqd3?file=%2Fpackage.json%3A17%2C92) as reported(meaning it wasn't fixed?), so maybe someone else can spend some time to verify if this fixes the problem reported?

**Review by langz — CHANGES_REQUESTED** [review]
Great, thanks 👍 

I've forked the [CSB](https://codesandbox.io/p/sandbox/nested-section-validation-issue-6mrxmv?file=%2Fsrc%2FApp.tsx%3A50%2C9) from the [issue](https://github.com/dnbexperience/eufemia/issues/3797) @andlbrei reported, and made a new [CSB using this fix](https://codesandbox.io/p/sandbox/nested-section-validation-issue-forked-55wqd3?file=%2Fpackage.json%3A17%2C92) that can be used to validate if the fixes work as expected or not 👍 


I might not understand the problem entirely, as I felt like I experienced the same issue in the [CSB using this fix](https://codesandbox.io/p/sandbox/nested-section-validation-issue-forked-55wqd3?file=%2Fpackage.json%3A17%2C92) as in the [CSB reported](https://codesandbox.io/p/sandbox/nested-section-validation-issue-6mrxmv?file=%2Fsrc%2FApp.tsx%3A50%2C9)(meaning it wasn't fixed?), so maybe someone else can spend some time to verify if this fixes the problem reported?

**Comment by andlbrei** [comment]
@langz I agree, cancelling in step 1 of your CSB does not restore the state from before the edit container was opened.

**Comment by andlbrei** [comment]
@langz Actually, your new CSB does not use the build you referenced. Using the correct build this seems to be fixed.

**Review by andlbrei — APPROVED** [review]
👍

**Comment by langz** [comment]
Great, thanks :) 

No idea how I was able to use the wrong hash, thanks for testing :)

**Review by langz — APPROVED** [review]

**Comment by langz** [comment]
I found a new case, which I don't understand, I get the error message "Feilene ovenfor må rettes", but not sure what's "wrong".

https://github.com/user-attachments/assets/bb025a91-ec7f-445b-b72e-43641239b09e

**Comment by langz** [comment]
After this branch got rebased with main, I made [an other CSB](https://codesandbox.io/p/sandbox/nested-section-validation-issue-forked-r8xsk4), using build a5518ea0, and I was not able to reproduce the following error 🥳

**Pull request merged**
