### PR TITLE
chore: rename screenshot tests

### PR DESCRIPTION
**Pull request by langz**

### CODE REVIEW

**Review by tujoworker — APPROVED** [review]
Nice finding! We need to remove all png files inside the snapshots folder for the renamed tests – and generate them again. Because they use the test names for the file names. But sadly there is no automation. Yes, I agree, its a little bit cumbersome.

We need anyway to consider to mover over to [jest-image-snapshot](https://github.com/americanexpress/jest-image-snapshot) – they support `customSnapshotIdentifier`. Even if ours is 10x faster, the [docs say](https://github.com/Prior99/jest-screenshot) – it does not support a [custom file name](https://github.com/Prior99/jest-screenshot/issues/71).

**Comment by langz** [comment]
> Nice finding! We need to remove all png files inside the snapshots folder for the renamed tests – and generate them again. Because they use the test names for the file names. But sadly there is no automation. Yes, I agree, its a little bit cumbersome.
> 
> We need anyway to consider to mover over to [jest-image-snapshot](https://github.com/americanexpress/jest-image-snapshot) – they support `customSnapshotIdentifier`. Even if ours is 10x faster, the [docs say](https://github.com/Prior99/jest-screenshot) – it does not support a [custom file name](https://github.com/Prior99/jest-screenshot/issues/71).

I'll remember to also remove the "old files" as well 🙏

**Pull request merged**
