### PR TITLE
fix(NumberFormat): improve regex for parsing phone numbers with country codes

### LINKED ISSUE #4337: bug(Value.PhoneNumber): Formats value weirdly for some country prefixes
## 🐛 Bug Report

Some country prefixes are formatted weirdly in the Value.PhoneNumber component, such as +1, +1-264 and +682.

## To Reproduce

https://codesandbox.io/p/sandbox/eufemia-phonenumber-problems-with-field-and-value-x854fy

## Expected behavior

For the number +1 123123123 I would expect the Value.PhoneNumber to output something like +1 123 123 213, but instead it outputs +11 23 12 32 13. It looks like it expects all country prefixes to be 2 digits, but i fact it can be other things as well.

## Run `npx envinfo`

Paste the results here:

```bash

  System:
    OS: macOS 15.1.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 92.98 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/Library/pnpm/nodejs/20.11.1/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
    pnpm: 9.14.2 - ~/.nvm/versions/node/v20.15.0/bin/pnpm
  Managers:
    Homebrew: 4.4.1 - /opt/homebrew/bin/brew
    pip3: 24.0 - /opt/homebrew/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 16.0.0 - /usr/bin/gcc
    Git: 2.45.1 - /opt/homebrew/bin/git
    Clang: 16.0.0 - /usr/bin/clang
    Curl: 8.7.1 - /usr/bin/curl
    OpenSSL: 3.3.0 - /opt/homebrew/bin/openssl
  Servers:
    Apache: 2.4.62 - /usr/sbin/apachectl
  Virtualization:
    Docker: 27.0.3 - /usr/local/bin/docker
  IDEs:
    IntelliJ: 2024.2.3
    VSCode: 1.95.3 - /usr/local/bin/code
    Vim: 9.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 21.0.4 - /Users/torrytufteland/.sdkman/candidates/java/current/bin/javac
    Perl: 5.34.1 - /usr/bin/perl
    Python3: 3.12.3 - /opt/homebrew/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  Databases:
    SQLite: 3.43.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 131.0.6778.86
    Edge: 131.0.2903.63
    Safari: 18.1.1
```

## Eufemia Version

10.57.1

### PR DESCRIPTION
**Pull request by tujoworker**
Fixes #4337

### CODE REVIEW

**Review by langz — APPROVED** [review]
Nice :) 
Can it format phone number with 3-digit country code?
Like Finland `+358`?

**Comment by langz** [comment]
> > Like Finland +358?
> 
> 
> 
> yes. Added test for that too.

How about Bermuda? Hehe
+1-441. Or Jersey +44-1534

Or Puerto Rico seems weird:
image

**Comment by tujoworker** [comment]
I see. We have had one invalid entry. That said, we don't support multiple country codes today.

There are several Zone 1 countries with two or three country code in [this list](https://en.wikipedia.org/wiki/List_of_country_calling_codes):

Screenshot 2024-11-25 at 22 52 27
Screenshot 2024-11-25 at 22 53 38
Screenshot 2024-11-25 at 22 53 43

**Pull request merged**
