### PR TITLE
docs: separate infinityscroller from pagination

### PR DESCRIPTION
**Pull request by dinarosv**
Since the `mode='infinity'` is a special use case of Pagination, I suggest to separate it out in a new subpage to leave Pagination clean for those who are looking to only use `mode='pagination'`.

### CODE REVIEW

**Comment by dinarosv** [comment]
Anyone have ideas why the subpage is put under Skeleton? The folder+files is under Pagination 🤔

**Review by thaytharma — COMMENTED** [review]
I think this is a great improvement! @dinarosv 😊 

I have two suggestions:

- Change `InfinityScroller` to be a subpage of `Pagination` (instead of `Skeleton`) in the navigation menu.
EDIT: Just saw your comment: https://github.com/dnbexperience/eufemia/pull/1223#issuecomment-1022131377 will try to look into it if I can! 😊
- Add `InfinityScroller` to the '/components'-page (like we did with the `Drawer`).

What do you think?

**Comment by dinarosv** [comment]
> * Add `InfinityScroller` to the '/components'-page (like we did with the `Drawer`).
> 
> What do you think?

Great idea, will add that now! 😊

**Comment by thaytharma** [comment]
> Anyone have ideas why the subpage is put under Skeleton? The folder+files is under Pagination 🤔

Debugged this a bit @dinarosv 
When fixing the `order` of the components it seems to be working. 😊
Some of them have the same `order`-value.

**Comment by dinarosv** [comment]
@tujoworker Can you help me run Gatsby build service on this again? Don't know why it failed 🤔

**Review by tujoworker — APPROVED** [review]
Looks good 🙌

**Comment by tujoworker** [comment]
> @tujoworker Can you help me run Gatsby build service on this again? Don't know why it failed 🤔
Screenshot 2022-01-31 at 10 54 11

The re-run button on GitHub seems not to trigger a new build. Try either to squash the first two commits, as they are pretty much the same, or push an empty commit.

**Review by thaytharma — APPROVED** [review]
Great work! 😍

**Pull request merged**
