### PR TITLE
fix(DatePicker): fix text prop for submit and cancel buttons

### PR DESCRIPTION
**Pull request by joakbjerk**
## Summary

Solves [this issue](https://github.com/dnbexperience/eufemia/issues/2190) where developers were unable to change the submit and cancel button text

### CODE REVIEW

**Review by tujoworker — APPROVED** [review]
Looks good to me 👌

**Comment by joakbjerk** [comment]
> Nice, this looks great 👏 Should we perhaps add tests for these "new" props as well? 🤔

Made tests for the custom text props @langz  @tujoworker please double check if they are done correctly 🙏

**Comment by langz** [comment]
> > Nice, this looks great 👏 Should we perhaps add tests for these "new" props as well? 🤔
> 
> Made tests for the custom text props @langz @tujoworker please double check if they are done correctly 🙏

Thanks, looks great.
Only "improvement" or possible change I would consider is to have one render for each it statement, where we only include the props needed for the it statement.
Like for the it statement, `should show custom text for submit button`, I would consider only doing:
`  render(
    <Component
      opened
      label="Custom submit text"
      show_input
      submit_button_text="Yes"
      show_submit_button
    />
  )`
  
  Assuming these are the only props needed to test the it statement 🙏

**Review by langz — APPROVED** [review]

**Comment by joakbjerk** [comment]
> > > Nice, this looks great 👏 Should we perhaps add tests for these "new" props as well? 🤔
> > 
> > 
> > Made tests for the custom text props @langz @tujoworker please double check if they are done correctly 🙏
> 
> Thanks, looks great 🚀 Only "improvement" or possible change I would consider is to have one render for each it statement, where we only include the props needed for the it statement. Like for the it statement, `should show custom text for submit button`, I would consider only doing:
> 
> ```
> render(
>     <Component
>       opened
>       label="Custom submit text"
>       show_input
>       submit_button_text="Yes"
>       show_submit_button
>     />
>   )
> ```
> 
> Assuming these are the only props needed to test the it statement 🙏
> 
> This is not important at all, just a suggestion as I would rather prefer smaller/easier to read "renders" containing only what's needed for the given it statement, instead of having one large render that covers many different tests/it statements.

Great suggestion, will change it now 🔥

**Pull request merged**
