### PR TITLE
fix(Autocomplete): make click on data suffix-element opening the drawer-list

### PR DESCRIPTION
**Pull request by tujoworker**
Issue [thread](https://dnb-it.slack.com/archives/CMXABCHEY/p1660127051200229).

The additional suffix value was not "clickable". 

With this PR, the element is "clickable" and opens the drawer-list. Also, its still possible to select the value for copy&paste. And a second click will not close it.

### CODE REVIEW

**Comment by langz** [comment]
I was not able to open the drawer-list by clicking on the suffix value, tested in the deploy preview.
See the attached video.

https://user-images.githubusercontent.com/1359205/184619866-09592c46-fb9b-4933-9410-50f2359c6774.mov

**Review by langz — COMMENTED** [review]
I was not able to open the drawer-list by clicking on the suffix value(As far as I understood this was one of the desired features?), tested in the deploy preview(Might be something wrong with the deploy preview?).
https://eufemia-fixautocompletereactivesuffix.gtsb.io/uilib/components/autocomplete/#data-suffix-value

See the attached video.

https://user-images.githubusercontent.com/1359205/184619866-09592c46-fb9b-4933-9410-50f2359c6774.mov

**Comment by tujoworker** [comment]
@langz ohh, good catch 🤩 Lets check if the changes make better this time. I see that I also did not take account for a disabled state. That's covered now as well.

**Review by langz — APPROVED** [review]
Looked even better this time around, nicely done 🥇

**Pull request merged**
