### PR TITLE
chore(Portal): replace React Helmet with the new Gatsby Head API

### PR DESCRIPTION
**Pull request by tujoworker**
Following the docs: https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/

### CODE REVIEW

**Review by langz — APPROVED** [review]
Looks great 💯 
I did however encounter a few console errors when running the application locally at http://localhost:8000/ 

Not sure if it's something new or something worth looking into.

Error:

```
react-dom.development.js:67 Warning: Prop `aria-atomic` did not match. Server: "null" Client: "true"
    at span
    at span
    at AutocompleteInstance (webpack-internal:///../dnb-eufemia/src/components/autocomplete/Autocomplete.js:319:5)
    at DrawerListProvider (webpack-internal:///../dnb-eufemia/src/fragments/drawer-list/DrawerListProvider.js:47:5)
    at Autocomplete (webpack-internal:///../dnb-eufemia/src/components/autocomplete/Autocomplete.js:74:5)
    at eval (webpack-internal:///../../node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at eval (webpack-internal:///../../node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at SearchBarInput (webpack-internal:///./src/shared/menu/SearchBar.js:44:38)
    at div
    at eval (webpack-internal:///../../node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at nav
    at eval (webpack-internal:///../../node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at MainWrapper (webpack-internal:///./src/shared/menu/MainMenu.js:64:5)
    at MainMenu (webpack-internal:///./src/shared/menu/MainMenu.js:162:34)
    at MainMenuProvider (webpack-internal:///./src/shared/menu/MainMenuContext.js:42:5)
    at main
    at App (webpack-internal:///./src/docs/index.js?export=default:28:1)
    at PageRenderer (webpack-internal:///./.cache/page-renderer.js:32:82)
    at PageQueryStore (webpack-internal:///./.cache/query-result-store.js:45:5)
    at RouteHandler
    at div
    at FocusHandlerImpl (webpack-internal:///../../node_modules/@gatsbyjs/reach-router/es/index.js:360:5)
    at FocusHandler (webpack-internal:///../../node_modules/@gatsbyjs/reach-router/es/index.js:331:19)
    at RouterImpl (webpack-internal:///../../node_modules/@gatsbyjs/reach-router/es/index.js:236:5)
    at Location (webpack-internal:///../../node_modules/@gatsbyjs/reach-router/es/index.js:65:23)
    at Router
    at ScrollHandler (webpack-internal:///../../node_modules/gatsby-react-router-scroll/scroll-handler.js:87:35)
    at RouteUpdates (webpack-internal:///./.cache/navigation.js:278:5)
    at EnsureResources (webpack-internal:///./.cache/ensure-resources.js:31:5)
    at LocationHandler (webpack-internal:///./.cache/root.js:52:1)
    at LocationProvider (webpack-internal:///../../node_modules/@gatsbyjs/reach-router/es/index.js:85:5)
    at Location (webpack-internal:///../../node_modules/@gatsbyjs/reach-router/es/index.js:65:23)
    at Root
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at MDXScopeProvider (webpack-internal:///./node_modules/gatsby-plugin-mdx/context.js:79:3)
    at _c (webpack-internal:///./node_modules/gatsby-plugin-mdx/wrap-root-element.js:107:15)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:122:48)
    at SkeletonEnabled (webpack-internal:///./src/core/PortalStylesAndProviders.js:93:3)
    at Provider (webpack-internal:///../dnb-eufemia/src/shared/Provider.tsx:176:5)
    at PartytownProvider (webpack-internal:///../../node_modules/gatsby/dist/internal-plugins/partytown/gatsby-browser.js:17:3)
    at StaticQueryStore (webpack-internal:///./.cache/query-result-store.js:138:5)
    at ErrorBoundary (webpack-internal:///./.cache/fast-refresh-overlay/components/error-boundary.js:19:5)
    at DevOverlay (webpack-internal:///./.cache/fast-refresh-overlay/index.js:137:3)
    at RootWrappedWithOverlayAndProvider
    at App (webpack-internal:///./.cache/app.js:165:50)
```

**Comment by tujoworker** [comment]
> I did however encounter a console error when running the application locally

Yeah, Gatsby did enable [FAST_DEV in v4.18](https://github.com/gatsbyjs/gatsby/discussions/28138#discussioncomment-2999877) – that means, SSR runs during development.
 
In this PR we update to v4.20 – how ever, we may look into this specific warning and fix it. But I guess there will be warnings several other places. 
Its all about that the SSR generated VDOM not matches with the client side generated. Like if we generate a random ID (many places we do that) then the VDOM will never match anyway. And we get a warning. 

In React v18 there is a hook we can use, called `useId`. But this one we first can use when we ban v17 usage and have converted everything to functional components, that support Hooks. So a lot of work.

So I think we may disable FAST_DEV i gatsby-config for now.

**Comment by langz** [comment]
> 

Thanks for looking into this, and explaining it 👏

**Pull request merged**
