### PR TITLE
chore: removes new status from components older than 10 months

### PR DESCRIPTION
**Pull request by langz**
This PR removes `new` status from components older than 10 months(based on git blame).
The only component left with `new` status now is the Layout component.

### CODE REVIEW

**Review by joakbjerk — APPROVED** [review]
💯

**Review by tujoworker — APPROVED** [review]
Nice! I suggest to mark the Section component as "new" (or updated?) because it got almost a 100% rewrite and can be used for very new things (responsive layouts).

**Comment by langz** [comment]
> Nice! I suggest to mark the Section component as "new" (or updated?) because it got almost a 100% rewrite and can be used for very new things (responsive layouts).

Thanks, great, I've added the status new to Section in the following PR https://github.com/dnbexperience/eufemia/pull/3045

**Pull request merged**
