### PR TITLE
feat(forms): add `dataPath` prop to Field.Selection

### PR DESCRIPTION
**Pull request by tujoworker**

### CODE REVIEW

**Review by langz — APPROVED** [review]
🚀

**Comment by joakbjerk** [comment]
Maybe I'm not testing correctly (or misunderstand something 😅) but the Selection does not seem to populate options correctly when using `dropdown` or `autocomplete` varaint
Screenshot 2024-08-13 at 14 25 29
Screenshot 2024-08-13 at 14 24 02

**Review by joakbjerk — APPROVED** [review]
Nice, looks good 🚀

**Pull request merged**
