### PR TITLE
chore(Selection): adds dynamic options example

### PR DESCRIPTION
**Pull request by henit**
Showing how Selection-options can be created and rendered dynamically

### CODE REVIEW

**Review by langz — APPROVED** [review]
Code looks good to me 💯

**Comment by henit** [comment]
> I gave it a quick test in the [deploy preview](https://eufemia-git-fix-forms-dynamic-selection-options-example-eufemia.vercel.app/uilib/extensions/forms/base-fields/Selection/demos/#dynamic-options), and I did experience if I had selected `Option 3`, then clicked the button for `4 options` that It was not possible to selection `Option 4`. It just shows `Valgmeny` after I select `Option 4`. Take a look at the video below:
> 
>  Screen.Recording.2023-12-12.at.10.25.39.mov 
> Not sure if this observation is "disturbing" or "ruining" the purpose of the example or not. Could be that my observation doesn't matter, and is not worth looking into 🙏

I see that the inner Dropdown component render receives the new value when clicking the 4th option, so maybe a bug in Dropdown?

**Review by tujoworker — APPROVED** [review]

**Comment by langz** [comment]
> > I gave it a quick test in the [deploy preview](https://eufemia-git-fix-forms-dynamic-selection-options-example-eufemia.vercel.app/uilib/extensions/forms/base-fields/Selection/demos/#dynamic-options), and I did experience if I had selected `Option 3`, then clicked the button for `4 options` that It was not possible to selection `Option 4`. It just shows `Valgmeny` after I select `Option 4`. Take a look at the video below:
> > Screen.Recording.2023-12-12.at.10.25.39.mov
> > Not sure if this observation is "disturbing" or "ruining" the purpose of the example or not. Could be that my observation doesn't matter, and is not worth looking into 🙏
> 
> I see that the inner Dropdown component render receives the new value when clicking the 4th option, so maybe a bug in Dropdown?

Thanks for checking it out.
Yes, that could be 😱 🙀

**Pull request merged**
