### PR TITLE
fix(Field.Selection): add error state and message

### PR DESCRIPTION
**Pull request by joakbjerk**
Proposal to fix https://github.com/dnbexperience/eufemia/issues/3039.

Not sure if wrapping the `Radio.Group` inside a `FieldBlock` or if the current approach is the best way to solve it. Please discuss 🙏

Before:
Screenshot 2023-12-13 at 14 59 12

After:
Screenshot 2023-12-13 at 14 58 56

### CODE REVIEW

**Comment by langz** [comment]
Nice nice, to me, this approach looks good 👍 

But we should probably check in the existing forms code, if there's other examples of `Radio.Group`, `ToggleButton.Group` or similar components that's wrapped in a `FieldBlock`. If it exists, I guess we should do so 🤔

**Review by langz — COMMENTED** [review]
Nice nice, to me, this approach looks good 👍 

But we should probably check in the existing forms code, if there's other examples of `Radio.Group`, `ToggleButton.Group` or similar components that's wrapped in a `FieldBlock`. If it exists, I guess we should do so 🤔

**Comment by tujoworker** [comment]
I have taken a look on this. And found that we need a slightly larger restructure. 

I may commit these changes if that is ok?

**Review by tujoworker — APPROVED** [review]

**Pull request merged**
