### PR TITLE
chore: fix Portal scroll position issues when using React v18

### PR DESCRIPTION
**Pull request by tujoworker**

### CODE REVIEW

**Review by langz — APPROVED** [review]
Thanks for fixing this, looks great 👏 
I believe this fixed the "jumping of the scroll bar" when navigating between different pages/sidebar-menu items, like experienced when pressing "best practices" and "avatar" in the video below:
https://github.com/dnbexperience/eufemia/assets/1359205/37d18147-de8f-4fe6-86ba-b30b1e63d527


While testing, I found an other "scroll to sidebarmenu item"-bug that I believe worked earlier/previously(sometime in v9). If I remember correct, when clicking on the "Checkbox"-link in the video below, the user should be "auto scrolled" to the active item in the sidebarmenu, which should be checkbox:

https://github.com/dnbexperience/eufemia/assets/1359205/f6667c65-264f-4cab-9b12-e5d2bcfbf9f7

**Comment by tujoworker** [comment]
You are right! Let me fix that 🫶

**Comment by langz** [comment]
> @langz could you check it out again?

Yes, I think it works perfect now ⭐ 🌟 

I did experience one thing, which I do believe is working on the latest deployed version to https://eufemia.dnb.no/, and that's when scrolling down a page with lots of content, then changing to a new page, I wouldn't get to the top of the new page:


https://github.com/dnbexperience/eufemia/assets/1359205/672f7354-1b94-47ea-bf76-5c74f9c234a3


Not sure if this is related to these changes though 🤔

**Comment by tujoworker** [comment]
Nice finding! It should work fine now with [this fix](https://github.com/tujoworker/gatsby-plugin-scroll-position/pull/10) 🙏

**Pull request merged**
