### PR TITLE
fix(Forms): enhance reset routine of ChildrenWithAge block

### PR DESCRIPTION
**Pull request by tujoworker**
Instead of resetting the amount of children, this PR removes it, so the default value applies when switching back again.

### CODE REVIEW

**Comment by langz** [comment]
Just gave it a quick [testrun](https://eufemia-git-feat-enhance-children-with-age-eufemia.vercel.app/uilib/extensions/forms/blocks/ChildrenWithAge/demos/#in-wizard), and it sort of acts a bit strange now :P


https://github.com/user-attachments/assets/7e843439-dcc4-47fa-ae73-5ee807efc9c0

**Comment by langz** [comment]
I just have an observation when comparing with our [portal](https://eufemia.dnb.no/uilib/extensions/forms/blocks/ChildrenWithAge/#in-wizard), and that's that now, the form don't remember what I previously entered when I switch between pressing "Ja" and "Nei" in the "Har du/dere barn under 18 år?"-question. I'm not sure if this was introduced in this PR, or one of the other related ones we've merged to main.
Not saying this is wrong, I'm just reporting the observation 🕵️ 

Here's a video from our [portal](https://eufemia.dnb.no/uilib/extensions/forms/blocks/ChildrenWithAge/#in-wizard):


https://github.com/user-attachments/assets/b235ae66-9dc6-4951-98c1-c75a44973392



Here's a video from the [deploy preview of this PR](https://eufemia-git-feat-enhance-children-with-age-eufemia.vercel.app/uilib/extensions/forms/blocks/ChildrenWithAge/#in-wizard):


https://github.com/user-attachments/assets/77c1da1a-8837-4843-a9a9-59c9dae09f5d

**Comment by tujoworker** [comment]
Yes, I like the portal version 💯 better. By now I could not find a better solution regarding the "sync" between the two modes (summary). But I will give it another thought.

**Comment by tujoworker** [comment]
Maybe this is not a real problem. It appears only if `showEmpty` is used.

**Comment by tujoworker** [comment]
I have a solution that is better. In involves both these PRs:

- #3965
- #3964

**Comment by tujoworker** [comment]
@langz Can you check out how the new solutions works out for you? ([demos](https://eufemia-git-feat-enhance-children-with-age-eufemia.vercel.app/uilib/extensions/forms/blocks/ChildrenWithAge/#in-wizard))

**Comment by langz** [comment]
> @langz Can you check out how the new solutions works out for you? ([demos](https://eufemia-git-feat-enhance-children-with-age-eufemia.vercel.app/uilib/extensions/forms/blocks/ChildrenWithAge/#in-wizard))

I'll give it a test🫡🤞

**Comment by langz** [comment]
> > @langz Can you check out how the new solutions works out for you? ([demos](https://eufemia-git-feat-enhance-children-with-age-eufemia.vercel.app/uilib/extensions/forms/blocks/ChildrenWithAge/#in-wizard))
> 
> I'll give it a test🫡🤞

Give it a go, and it works perfect now🫡

**Pull request merged**
