### PR TITLE
chore(Img): move to own subfolder

### PR DESCRIPTION
**Pull request by joakbjerk**

### CODE REVIEW

**Comment by tujoworker** [comment]
We have this build error:

`Attempted import error: 'Img' is not exported from '@dnb/eufemia/src/elements' (imported as 'Image').`

**Comment by tujoworker** [comment]
I don't think we should rename the component in this PR. My arguments are; its a tiny wrapper. Its based on the HTML `img` tag. A project would rather user `Image` for their component names. With good reasons for good naming.

**Comment by tujoworker** [comment]
@joakbjerk could you rebase this branch from origin/v10? So the Vercel builds don't fail.

**Review by langz — APPROVED** [review]
Looks good to me 👓 🥳

**Review by tujoworker — CHANGES_REQUESTED** [review]
It looks like the PR needs to be rebased properly 🙏

**Review by tujoworker — APPROVED** [review]

**Pull request merged**
