### PR TITLE
fix(Autocomplete): pass status props to SubmitButton

### PR DESCRIPTION
**Pull request by langz**
From:
image

To: 
image

### CODE REVIEW

**Review by tujoworker — APPROVED** [review]
I would love if the new tests would use testing lib instead of enzyme. I know, you prefer consistency. But we need to do the transformation because of React v18 very soon anyways 😉

**Comment by langz** [comment]
> I would love if the new tests would use testing lib instead of enzyme. I know, you prefer consistency. But we need to do the transformation because of React v18 very soon anyways 😉

Done :)

**Pull request merged**
