### PR TITLE
fix(ToggleButton): add checked disabled style

### PR DESCRIPTION
**Pull request by joakbjerk**
proposal to solve https://github.com/dnbexperience/eufemia/issues/3028 and https://github.com/dnbexperience/eufemia/issues/3027

Not sure if its the best way though.

before:
Screenshot 2024-01-15 at 10 12 42

after:
Screenshot 2024-01-15 at 10 12 22

### CODE REVIEW

**Review by tujoworker — APPROVED** [review]
Looks good! Did you check the Sbanken styles?

**Comment by tujoworker** [comment]
Also, do we have a visual test on the disabled state? Then we may add a "checked" example state in there as well (same test).

**Comment by joakbjerk** [comment]
I'll add the same to Sbanken and add visual tests 🙏

**Comment by tujoworker** [comment]
I added a commit. We actually had a visual test for the disabled state. So we just need to make one of them as "selected".

**Pull request merged**
