### PR TITLE
feat(Forms): add inline HelpButton to all Field.* components as default (with option to open in Dialog)

### PR DESCRIPTION
**Pull request by tujoworker**
This PR changes the existing behavior of the `help` prop for Fields that previously supported it. The content now opens inline instead of in a Dialog.

The `help` prop has now all of these optional props:

```tsx
<Field.String
  label="Label text"
  help={{
    title: 'Help is available',
    content:
      'Take the time to help other people without expecting a reward or gratitude is definitely important in living an optimistic life.',
    open: false,// only for the inline variant
    renderAs: 'dialog'
  }}
/>
```

We use this prop description:

> Provide help content for the field using `title` and `content` as a string or React.Node. Additionally, you can set `open` to `true` to display the inline help or use `renderAs` set to `dialog` to render the content in a [Dialog](/uilib/components/dialog/) (recommended for larger amounts of content).
 
Examples with inline "HelpButton":

- [FieldBlock](https://eufemia-git-feat-forms-inline-help-button-eufemia.vercel.app/uilib/extensions/forms/create-component/FieldBlock/demos/#inline-help-button-vertical-only) (several examples)
- [Form.MainHeading](https://eufemia-git-feat-forms-inline-help-button-eufemia.vercel.app/uilib/extensions/forms/Form/MainHeading/#with-helpbutton)
- [Form.SubHeading](https://eufemia-git-feat-forms-inline-help-button-eufemia.vercel.app/uilib/extensions/forms/Form/SubHeading/#with-helpbutton)
- [Field.String](https://eufemia-git-feat-forms-inline-help-button-eufemia.vercel.app/uilib/extensions/forms/base-fields/String/#with-help)
- [Field.Number](https://eufemia-git-feat-forms-inline-help-button-eufemia.vercel.app/uilib/extensions/forms/base-fields/Number/#with-help)
- [Field.Upload](https://eufemia-git-feat-forms-inline-help-button-eufemia.vercel.app/uilib/extensions/forms/feature-fields/more-fields/Upload/#with-help)
- ... many other fields do have an example as well.

**NB:** We do not document the internals of the inline version at this time. This can be included in another PR. The reason is that it would require additional tests, examples, and documentation. It is also an "isolated" feature specific to the HelpButton. However, as of this writing, I am unsure if we will ever document it, as integration is not straightforward. There are several considerations to address when implementing it.

### CODE REVIEW

**Comment by langz** [comment]
When clicking the question mark and opening, the question mark changes to an x which animates. 
Then when clicking the x and closing, it just changes to the question mark. 
Should it do the reverse of when opening, to animate the x back, before displaying question mark?


This is just thoughts, not very important to me. 

https://github.com/user-attachments/assets/fa233cec-6aa1-42bd-92fb-6338572cec0a

**Comment by langz** [comment]
I tested tabbing with keyboard, and it works great 👍 
Found one edge-case when using enter/space to opening the help text, in the following example: https://eufemia-git-feat-forms-inline-help-button-eufemia.vercel.app/uilib/extensions/forms/create-component/FieldBlock/demos/#inline-help-button-vertical-label-description


https://github.com/user-attachments/assets/5d36b952-a72b-4107-9ad3-b1f2e1227a55

**Comment by langz** [comment]
I tested the following [example](https://eufemia-git-feat-forms-inline-help-button-eufemia.vercel.app/uilib/extensions/forms/base-fields/Composition/demos/#composition-field) with the following code:

```
<Field.Composition info="Info at the bottom" width="large">
  <Field.String label="Field A with a long label" width="medium" help={{
    title: 'Help title',
    content: 'Help content',
  }}/>
  <Field.String label="Field B" width="stretch" help={{
    title: 'Help title',
    content: 'Help content',
  }} />
</Field.Composition>
```

And for the field with `width="stretch"` the help text appeared in the opposite way then usual:


https://github.com/user-attachments/assets/24bbe9d7-295b-400e-a021-4b8c9c8bef6a

**Comment by langz** [comment]
Should we add this `help` functionality to the ValueBlock as well?
Could see us doing so at a point, and perhaps even add `inheritHelp`

**Comment by langz** [comment]
[Field. BankAccountNumber when layout horizontal, changes position and/or width when opening/closing the help:](https://codesandbox.io/p/sandbox/modest-nightingale-y22rqw?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)


https://github.com/user-attachments/assets/7c815c5a-e264-4fe6-bc62-ac6af1583a87

**Comment by langz** [comment]
Here's a CSB displaying some possible alignment issues when using help with layout vertical for fields that have two fields.
https://codesandbox.io/p/sandbox/funny-ishizaka-sgcp6x?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd

image

**Comment by tujoworker** [comment]
I think I have covered now all of your fantastic feedback.

The rotation animation runs now also when hiding the help content.

Some fields do not support a horizontal layout, such as PostcalCode and PhoneNumber. But also Composition does not support it.

**Comment by langz** [comment]
I've forked and updated the eufemia version to be of latest commit in this PR for the following CSBs:
- [Card vertical](https://codesandbox.io/p/sandbox/nifty-booth-rvkvt2?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)
- [BankAccountNumber vertical](https://codesandbox.io/p/sandbox/autumn-glade-r4n5v6?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)
- [All fields horizontal](https://codesandbox.io/p/sandbox/elastic-tom-zxhk2r?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)
- [All field vertical](https://codesandbox.io/p/sandbox/infallible-lake-rg346k?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)

**Comment by langz** [comment]
> When clicking the question mark and opening, the question mark changes to an x which animates. Then when clicking the x and closing, it just changes to the question mark. Should it do the reverse of when opening, to animate the x back, before displaying question mark?
> 
> This is just thoughts, not very important to me, and I'm not 100% sure what's the correct behaviour here.
> 
>  trim.BBA79D28-B838-4F3B-8551-29D1D571C1F9.MOV

This looks great now ❤️

**Comment by langz** [comment]
> In the following examples
> 
> https://eufemia-git-feat-forms-inline-help-button-eufemia.vercel.app/uilib/extensions/forms/create-component/FieldBlock/demos/#inline-help-button-vertical-only
> 
> The animation feels a bit different than in https://eufemia-git-feat-forms-inline-help-button-eufemia.vercel.app/uilib/extensions/forms/create-component/FieldBlock/demos/#inline-help-button-vertical-only, it doesn't keep the spacing below the inline help text:
> 
>  trim.6603225A-06AE-48FC-809C-19FB8AA2ABDD.MOV 
> Image of animation at a point. Here we can see the top border of the input field is gone/covered: image
> 
> Because of this, it feels like it changes/does something with the top border of the input field(of course it does not, but visually it feels so, that it flashes):
> 
>  trim.2067C2DA-FF8C-4143-A5D5-F2A8815981B5.MOV

This looks great now 🚀

**Comment by langz** [comment]
> I tested tabbing with keyboard, and it works great 👍 Found one edge-case when using enter/space to opening the help text, in the following example: https://eufemia-git-feat-forms-inline-help-button-eufemia.vercel.app/uilib/extensions/forms/create-component/FieldBlock/demos/#inline-help-button-vertical-label-description
> 
> It only happens when spacing/entering, not when clicking. Sometimes it can be hard to reproduce, but double spacing/entering twice fast can lead to it, but is not necessary(in the video provided, I don't do it fast).
> 
> The issue/error is that it somehow focuses the section(?)-element inside the help text, which I don't think it should? As it doesn't do so when clicking with the mouse.
> 
>  Screen.Recording.2024-11-15.at.09.21.06.mov

I'm still able to reproduce this, but I'm not sure how important this is to fix, or if actually is anything to fix 🤔

**Comment by langz** [comment]
> [Field. BankAccountNumber when layout horizontal, changes position and/or width when opening/closing the help:](https://codesandbox.io/p/sandbox/modest-nightingale-y22rqw?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)
> 
> The same happens with almost all [feature fields](https://eufemia-git-feat-forms-inline-help-button-eufemia.vercel.app/uilib/extensions/forms/feature-fields/)
> 
>  Screen.Recording.2024-11-15.at.12.02.41.mov

I'm still able to reproduce this as well, https://codesandbox.io/p/sandbox/autumn-glade-r4n5v6?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd

**Comment by langz** [comment]
> Here's a CSB displaying some possible alignment issues when using help with layout vertical for fields that have two fields., in a card https://codesandbox.io/p/sandbox/funny-ishizaka-sgcp6x?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd
> 
> image
> It's like it takes a bit more width than the width of the input field.

I was able to reproduce this as well, https://codesandbox.io/p/sandbox/nifty-booth-rvkvt2?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd

**Comment by tujoworker** [comment]
> Thanks, sure, fine that we don't support horizontal layout in PostCodeAndCity, PhoneNumber, Composition, etc.
> But how could/should we say that to our users?
> In the docs, it seems like we should support it, at least for:

I have update the docs for the PostalCodeAndCity field. PhoneNumber is already taken care of.

> I'm still able to reproduce this, but I'm not sure how important this is to fix, or if actually is anything to fix 🤔

I'm not able to reproduce it anymore. Also, we already have `dnb-no-focus` to the section element. Not sure what I do wrong 😄

> I'm still able to reproduce this as well, https://codesandbox.io/p/sandbox/autumn-glade-r4n5v6?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd

Found another solution.

> Here's a CSB displaying some possible alignment issues when using help with layout vertical for fields that have two fields., in a card https://codesandbox.io/p/sandbox/funny-ishizaka-sgcp6x?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd

Also enhanced + added a visual test.

**Comment by langz** [comment]
Thanks for the updates @tujoworker 
I've forked and updated the Eufemia version to be of latest commit in this PR for the following CSBs:

- [Card vertical(can't remember what I used this for)](https://codesandbox.io/p/sandbox/peaceful-tess-rnxfhq?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)
- [BankAccountNumber vertical](https://codesandbox.io/p/sandbox/festive-chebyshev-fktttd?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)
- [All fields horizontal](https://codesandbox.io/p/sandbox/clever-architecture-3mwdf3?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)
- [All fields vertical](https://codesandbox.io/p/sandbox/loving-jasper-qv65nv?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)

I've not tested them yet.

**Comment by langz** [comment]
I quickly re-tested tabbing and openeing/closing with enter and space keys, and I feel it works worse now.
I'm not able to reproduce the active/focused state of the section(?), which is good, but when using space and enter now it works workse.
Using space, first time it opens, next time I do space it scrolls down the page(even though the button looks active/focused).
Using enter, first time it opens, next time I press enter it won't close (even though the button looks active/focused):

https://github.com/user-attachments/assets/c72715cf-e24f-455a-821f-f5a435ed4574




https://eufemia-git-feat-forms-inline-help-button-eufemia.vercel.app/uilib/extensions/forms/create-component/FieldBlock/demos/#inline-help-button-vertical-only

**Comment by langz** [comment]
Since last time I checked the CSBs, the [All fields horizontal latest commit](https://codesandbox.io/p/sandbox/clever-architecture-3mwdf3?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd) looks quite different from what it did in the [previous commit/change](https://codesandbox.io/p/sandbox/elastic-tom-zxhk2r?file=%2Fsrc%2FApp.tsx%3A6%2C15&workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd). 
Is it intentional that it doesn't use the full width anymore?

How it was:

image


How it is now:

image

**Comment by langz** [comment]
> Some fields do not support a horizontal layout, such as PostcalCode and PhoneNumber. But also Composition does not support it.

Do we have to support it in the future?
Does it today exist a component that you can wrap all fields in, and say `layout=horizontal`, like in the form.handler Field.Provider, etc? Probably `Field.Provider`. Wouldn't the form look very strange now, when some Fields support horizontal and other don't? Or perhaps those fields(postalCode and Phonenumber) looks best as vertical, even when in a form where all other fields are horizontal? 🤔

**Comment by langz** [comment]
> > Some fields do not support a horizontal layout, such as PostcalCode and PhoneNumber. But also Composition does not support it.
> 
> Do we have to support it in the future? Does it today exist a component that you can wrap all fields in, and say `layout=horizontal`, like in the form.handler Field.Provider, etc? Probably `Field.Provider`. Wouldn't the form look very strange now, when some Fields support horizontal and other don't? Or perhaps those fields(PostalCode and PhoneNumber) looks best as vertical, even when in a form where all other fields are horizontal? 🤔
> 
> Here's a [CSB using Field.Provider with layout horizontal.](https://codesandbox.io/p/sandbox/ecstatic-chatterjee-d66f2n?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)

When using Field.PostalCodeAndCity in a Field.Provider with layout="horizontal", I'm not able to input anything in the postalcode field 🤔 

https://codesandbox.io/p/sandbox/frosty-sky-mn7jdd?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd

**Comment by tujoworker** [comment]
> Using space, first time it opens, next time I do space it scrolls down the page(even though the button looks active/focused).
> Using enter, first time it opens, next time I press enter it won't close (even though the button looks active/focused):

We set focus on the section so screen readers can navigate in there and also get read out the text. Even if the content is placed on a different DOM order.
But also so we can show the "hover" state (larger than focus).
I added support for the enter/space key to close it again. From before we had support for esc key.

> Is it intentional that it doesn't use the full width anymore when layout is horizontal?

Yes. Not it is aligned on how the status messages looks. Same border radius too. I think this is the most logical way to display this information on in a consistent way.

> Do we have to support it in the future?

I have never seen any PhoneNumber etc. layout that could work with these fields. So as of now, this is how it is. Most horizontal layouts are used within a small part of the form. So we do not need to support necessarily all fields with that layout.

**Comment by langz** [comment]
> > Using space, first time it opens, next time I do space it scrolls down the page(even though the button looks active/focused).
> 
> > Using enter, first time it opens, next time I press enter it won't close (even though the button looks active/focused):
> 
> 
> 
> We set focus on the section so screen readers can navigate in there and also get read out the text. Even if the content is placed on a different DOM order.
> 
> But also so we can show the "hover" state (larger than focus).
> 
> I added support for the enter/space key to close it again. From before we had support for esc key.
> 
> 
> 
> > Is it intentional that it doesn't use the full width anymore when layout is horizontal?
> 
> 
> 
> Yes. Not it is aligned on how the status messages looks. Same border radius too. I think this is the most logical way to display this information on in a consistent way.
> 
> 
> 
> > Do we have to support it in the future?
> 
> 
> 
> I have never seen any PhoneNumber etc. layout that could work with these fields. So as of now, this is how it is. Most horizontal layouts are used within a small part of the form. So we do not need to support necessarily all fields with that layout.
> 
> 
> 
> 

Thanks Tobias, that sounds smart.

**Comment by langz** [comment]
Thanks again the updates @tujoworker 🚀 
I've forked and updated the Eufemia version to be of latest commit `24ab19b3 ` in this PR for the following CSBs:

- [Card vertical(can't remember what I used this for)](https://codesandbox.io/p/sandbox/peaceful-tess-rnxfhq?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)
- [BankAccountNumber vertical](https://codesandbox.io/p/sandbox/festive-chebyshev-fktttd?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)
- [All fields horizontal](https://codesandbox.io/p/sandbox/clever-architecture-3mwdf3?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)
- [All fields vertical](https://codesandbox.io/p/sandbox/loving-jasper-qv65nv?workspaceId=9eb653cb-4406-4b8f-bc96-714927cc7fcd)

**Review by langz — APPROVED** [review]
Thanks for the great job 👏 
Works perfect now :)

**Pull request merged**
