### PR TITLE
Fix/input focus color

### PR DESCRIPTION
**Pull request by tujoworker**
This PR fixes an issue where the focus state on inputs had a wrong color (sea-green -> emerald-green). Now, with that change, I run the visual tests with `colorThreshold` of 0 – and found that there are a good amount of snaptshos we should have updated before, but they where so suptile, that they dident got picked up. But its added on an extra commit.

### CODE REVIEW

**Review by dinarosv — APPROVED** [review]
Wow, even I could not see the difference 😄

**Comment by tujoworker** [comment]
Yes, no body has repored it, I just saw it when I changed the caret color on the textarea, that the textarea had an darker outline during focus state.

**Comment by tujoworker** [comment]
Here is the diff:

Screenshot 2021-11-25 at 11 20 19

**Pull request merged**
