### PR TITLE
fix(Icon): fix stopwatch icon (16px)

### LINKED ISSUE #1428: Stopwatch icon is corrupted
## 🐛 Bug Report

Stopwatch icon is cut on the bottom.

## To Reproduce

https://codesandbox.io/s/eufemia-stopwatch-icon-is-corrupted-09fxgd (https://09fxgd.csb.app/)

## Expected behavior

Stopwatch icon should not be cut on the bottom, and looks like similar to Stopwatch medium icon

## Eufemia Version

v. 9.26.0, v. 9.25.0

Previous OK version 9.24.0 
https://codesandbox.io/s/eufemia-stopwatch-icon-is-not-corrupted-v9-24-9cy5v9?file=/src/App.tsx

### PR DESCRIPTION
**Pull request by tujoworker**
closes #1428

### CODE REVIEW

**Comment by langz** [comment]
Thanks :)
Looks great, the icons is not cut off in the bottom anymore 💯 

image

**Comment by tujoworker** [comment]
We may rebase this PR with main when #1462 has landed.

**Comment by tujoworker** [comment]
Some notes: We run a visual comparison of icons, but only for `24px` icons – located [here](packages/dnb-eufemia/src/components/icon/__tests__/__snapshots__/icon-screenshot-test-js-icon-screenshot-have-to-match-all-secondary-icons-1-25470.snap.png) – there we do nothing about it. But I guess, even if we would have had a snapshot, the change is so small, it would probably event not be picked up with our current settings.

**Pull request merged**
