### PR TITLE
feat(ScrollView): add sbanken styling to scrollbar

### PR DESCRIPTION
**Pull request by joakbjerk**

### CODE REVIEW

**Review by tujoworker — CHANGES_REQUESTED** [review]
I think we should move also:

```css
--scrollbar-track-width: 0.5rem;
--scrollbar-thumb-width: 0.5rem;
```

as it can be a property to change by themes as well.

**Comment by tujoworker** [comment]
I think, we also can remove the properties from the portal sidebar menu, as they should be covered with this change. 

@joakbjerk Can you double check that?

**Comment by joakbjerk** [comment]
> I think, we also can remove the properties from the portal sidebar menu, as they should be covered with this change.
> 
> @joakbjerk Can you double check that?

can do

**Pull request merged**
