### PR TITLE
feat(Input): sbanken styling

### PR DESCRIPTION
**Pull request by snorrekim**
## Summary

Sbanken styling for input. Added screenshot tests for error state with button.

### CODE REVIEW

**Comment by snorrekim** [comment]
I used css variables extensively to make the css as lean as possible. 

The biggest hurdle though, was that Input is too dependant on the Button component. There should be a larger degree of separation, the button used in an input does not have enough in common with the regular button. At most it could use some common variables for color. Either we should make it possible to completely strip the Button component of styling, or we should not use it here, and just use a regular <button> element

**Comment by tujoworker** [comment]
I agree with you. I'll create a ticket for that.

**Review by tujoworker — APPROVED** [review]
Looks 100% good to me. Wonderful work 🚀

**Pull request merged**
