### PR TITLE
fix(Autocomplete): Show whole suggestion list after item selection

### PR DESCRIPTION
**Pull request by joakbjerk**
Closes https://github.com/dnbexperience/eufemia/issues/4058

- [x] Fix tests
- [x] Add test for new functionality

Before:

https://github.com/user-attachments/assets/c3551fe6-e3e5-4995-ac84-95212593331b

After:

https://github.com/user-attachments/assets/8f420888-eba2-4b9e-889f-b7c097d27cc1

### CODE REVIEW

**Comment by tujoworker** [comment]
Having a test that fails without the change, would be good 👍

**Review by tujoworker — APPROVED** [review]
Nice 🙏

**Review by langz — APPROVED** [review]
🫡

**Pull request merged**
