### PR TITLE
feat(Upload): adds custom `href` property to file object

### PR DESCRIPTION
**Pull request by langz**

### CODE REVIEW

**Comment by torryt** [comment]
This looks like an elegant solution 🤩 Question: if the file URL resource requires authentication through cookies, will the cookies be forwarded with this approach?

**Comment by torryt** [comment]
@langz We've done some searching on this, and cookies are not included in CORS requests. In our frontend API client we add `credentials: 'include'` to ensure cookies are passed along. Therefore this approach would not work for us, since the `href` don't allow any custom HTTP client logic as I understand it.

**Comment by langz** [comment]
> @langz We've done some searching on this, and cookies are [not included in CORS requests.](https://jakearchibald.com/2021/cors/#adding-credentials) In our frontend API client we add `credentials: 'include'` to ensure cookies are passed along. Therefore this approach would not work for us, since the `href` don't allow any custom HTTP client logic as I understand it.

Thanks for checking 🤝 
I can quite quickly change this to a `onFileClick` handler which you can use programatically to do what you want.

However in regards to https://github.com/dnbexperience/eufemia/issues/4355 and not having to pre-loaded all files in the form data, I think that I would have to make changes other places in the code base as well so the form will still be valid even though the form does not have the full file, etc, etc.

**Comment by langz** [comment]
I've replaced this PR with the following PR https://github.com/dnbexperience/eufemia/pull/4365

**Pull request closed without merging**
