### PR TITLE
fix(InfoCard): Allow InfoCard to get skeleton prop from context

### PR DESCRIPTION
**Pull request by langz**
Motivated by #1344

### CODE REVIEW

**Review by dinarosv — APPROVED** [review]

**Comment by langz** [comment]
Not exactly sure why, but it seems like the commit https://github.com/dnbexperience/eufemia/pull/1348/commits/0ddcfa45a19ceaf2dbce970f568732c7fc56189a causes some kind of type error in line 192 and 204 in InfoCard.tsx, also seen in the build.
https://github.com/dnbexperience/eufemia/runs/5543661280?check_suite_focus=true#step:8:383

**Comment by dinarosv** [comment]
> Not exactly sure why, but it seems like the commit [0ddcfa4](https://github.com/dnbexperience/eufemia/commit/0ddcfa45a19ceaf2dbce970f568732c7fc56189a) causes some kind of type error in line 192 and 204 in InfoCard.tsx, also seen in the build. https://github.com/dnbexperience/eufemia/runs/5543661280?check_suite_focus=true#step:8:383

Hmm, I will look into it !

**Comment by langz** [comment]
> > Not exactly sure why, but it seems like the commit [0ddcfa4](https://github.com/dnbexperience/eufemia/commit/0ddcfa45a19ceaf2dbce970f568732c7fc56189a) causes some kind of type error in line 192 and 204 in InfoCard.tsx, also seen in the build. https://github.com/dnbexperience/eufemia/runs/5543661280?check_suite_focus=true#step:8:383
> 
> Hmm, I will look into it !

Thanks for the help, looks great now :)

**Pull request merged**
