### PR TITLE
feat(Icons): add browser, digipass, envelope_open, laptop, mobile, money_left, teenager

### PR DESCRIPTION
**Pull request by langz**
This PR adds the following icons:
- `browser`
- `digipass_corporate`
- `digipass_private`
- `envelope_open`
- `laptop`
- `mobile`
- `money_left`
- `teenager`

Can be demoed here https://eufemia-git-icons-update-dec-23-eufemia.vercel.app/icons/#undefined
Should we add these icons to a "category"(Objects, Essentials, Actions, etc)?
I see that they are categorized as `undefined` for now. 

But in the [Figma Library](https://www.figma.com/file/2aNwT4Lbyt9hFmDv8k34yN/Eufemia---Icons?type=design&node-id=1-876&mode=design&t=fbdjL8YVwUxbzwFi-0) it seems like digipass icons, etc, should be listed under the category Objects 🤔

### CODE REVIEW

**Comment by langz** [comment]
Updating visual/screenshots now 🕐

**Review by tujoworker — APPROVED** [review]
Looks good! We need to update the visual snapshot locally. We may add back this features to be automatically generated, if you want. Just updating `icon` is 👍 

It looks like the tag we removed last time, is still in the Figma file 🤔 

Screenshot 2023-12-12 at 15 17 30

**Comment by langz** [comment]
> Looks good! We need to update the visual snapshot locally. We may add back this features to be automatically generated, if you want. Just updating `icon` is 👍
> 
> It looks like the tag we removed last time, is still in the Figma file 🤔
> 
> Screenshot 2023-12-12 at 15 17 30

[I've updated the visual snapshots now](https://github.com/dnbexperience/eufemia/pull/3064/commits/8115f4aae5d5fd8e254308f49319ed07d79e0c4b).
I did not find the word `recieve` in the Figma library, so it's probably hiding somewher 🤔  😂

**Comment by tujoworker** [comment]
I'v added a timeout on this GitHub Action. If you want, move it to a new PR. Or just keep it there 👍 

Screenshot 2023-12-12 at 20 45 39

**Pull request merged**
