### PR TITLE
fix(TableContainer): no space on empty foot + clip scrollbar

### PR DESCRIPTION
**Pull request by tujoworker**
Based on UX wish, this is how it looks with this change:
Screenshot 2022-12-19 at 10 47 33

and when empty:

Screenshot 2022-12-19 at 10 47 45

### CODE REVIEW

**Review by langz — APPROVED** [review]
Fancy fancy 💃 

So we only want to clip the scrollbar when using the TableContainer, and not for all tables?

I tried testing this PR on my phone, iPhone, and as we discovered on Friday, I was not able to see any scrollbars at all for any of our tables 🤔

**Comment by langz** [comment]
An other observation, which I don't think is directly related to this PR, but something else related to scroll bars(which don't exists on https://eufemia.dnb.no/ yet).

When opening this deploy preview on my phone, then opening the menu, it looks to be some issues maybe related to https://github.com/dnbexperience/eufemia/pull/1814/files#diff-f0adfb69cb45eb94b8016448bc17488f3e2ba81514c694b5ce0f34f4e245bc56R290 ?

image

**Comment by tujoworker** [comment]
For the `TableContainer` the scorllbar is inside, else it is outside.

Screenshot 2022-12-19 at 10 09 45

**Comment by tujoworker** [comment]
> it looks to be some issues maybe related to

ohh, yes! good catch!

**Pull request merged**
