### PR TITLE
chore(Field.Selection): concat `dataPath` with children

### PR DESCRIPTION
**Pull request by tujoworker**
As an addition to #3816

### CODE REVIEW

**Comment by joakbjerk** [comment]
All the labels on the radios seems to be connected to the first radio button, so clicking the others selects the first radio button every time 😄
https://github.com/user-attachments/assets/e16a9384-e5f8-4b5e-91c0-f8c2a6b8b82a

**Comment by tujoworker** [comment]
Nice findings! The latest commit fixes this issue, including tests who would have failed without the fix.

**Review by joakbjerk — APPROVED** [review]
Nice, looks good 🔥

**Pull request merged**
