### PR TITLE
feat(Forms): add support for `defaultValue` (and `value`) for fields used in `Iterate.Array`

### LINKED ISSUE #3882: Iterate does not use Field.defaultValue/value
## 🐛 Bug Report

When using `defaultValue` or `value` in `Field` within `Iterate` the value is displayed and validated, but not stored when "submitting" the contents of the `Iterate` container.

https://github.com/user-attachments/assets/fa24c62d-d910-43a0-8149-7d1508eb67e9

## To Reproduce

https://codesandbox.io/p/sandbox/iterate-defaultvalue-cdlmrl

## Expected behavior

I expect `defaultValue` and `value` to be stored when submittin to the array.  
Especially for `PushContainer`, where default values make the most sense to use.

## Eufemia Version

10.45.0

### PR DESCRIPTION
**Pull request by tujoworker**
Fixes #3882

### CODE REVIEW

**Comment by tujoworker** [comment]
@andlbrei  Is it possible for you to test this feature manually? Would be really nice to get this confirmation before merge 🙏

**Review by andlbrei — CHANGES_REQUESTED** [review]
As noted in DM with @tujoworker there is an issue when running the CSB used in the bug report. I tried adding a populated data object to the Form Handler, but it did not work then either.

```
TypeError
Cannot set properties of null (setting 'firstName')
Function.set
https://cdlmrl.csb.app/node_modules/json-pointer/index.js:101:18
    at eval (https://cdlmrl.csb.app/node_modules/
dnb/eufemia/extensions/forms/DataContext/Provider/Provider.js:406:28
    at eval (https://cdlmrl.csb.app/node_modules/
dnb/eufemia/extensions/forms/hooks/useFieldProps.js:937:99
commitHookEffectListMount
https://cdlmrl.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23150:26
invokeLayoutEffectMountInDEV
https://cdlmrl.csb.app/node_modules/react-dom/cjs/react-dom.development.js:25120:13
invokeEffectsInDev
https://cdlmrl.csb.app/node_modules/react-dom/cjs/react-dom.development.js:27351:11
commitDoubleInvokeEffectsInDEV
https://cdlmrl.csb.app/node_modules/react-dom/cjs/react-dom.development.js:27327:5
flushPassiveEffectsImpl
https://cdlmrl.csb.app/node_modules/react-dom/cjs/react-dom.development.js:27056:5
flushPassiveEffects
https://cdlmrl.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26984:14
performSyncWorkOnRoot
https://cdlmrl.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26076:3
flushSyncCallbacks
https://cdlmrl.csb.app/node_modules/react-dom/cjs/react-dom.development.js:12042:22
commitRootImpl
https://cdlmrl.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26959:3
commitRoot
https://cdlmrl.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26682:5
finishConcurrentRender
https://cdlmrl.csb.app/node_modules/react-dom/cjs/react-dom.development.js:25981:9
performConcurrentWorkOnRoot
https://cdlmrl.csb.app/node_modules/react-dom/cjs/react-dom.development.js:25809:7
workLoop
https://cdlmrl.csb.app/node_modules/scheduler/cjs/scheduler.development.js:266:34
flushWork
https://cdlmrl.csb.app/node_modules/scheduler/cjs/scheduler.development.js:239:14
MessagePort.performWorkUntilDeadline
https://cdlmrl.csb.app/node_modules/scheduler/cjs/scheduler.development.js:533:21
```

**Comment by tujoworker** [comment]
Yes, I committed a solution for the problem + tests.

@andlbrei Can you verify that it works? 🙏

**Review by andlbrei — APPROVED** [review]
Seems to work fine now 👍 Great work!

**Comment by andlbrei** [comment]
I tried the latest build in my project and found some different issue, I guess it's best to fix it in this MR. I could open a new issue if you'd like.

When adding multiple elements, it's not possible to remove elements. I guess it should be possible to have an empty list as well, if validation allows it, so I guess removing elements in general is not possible.

https://github.com/user-attachments/assets/3a46e4a9-6ff8-4503-b619-7604edc4e503

The other issue I am currently seeing if I can reproduce. It's the same error as before:
```
ERROR
Cannot set properties of null (setting 'phoneNumber')
TypeError: Cannot set properties of null (setting 'phoneNumber')
    at Function.set (webpack-internal:///../../node_modules/.pnpm/json-pointer@0.6.2/node_modules/json-pointer/index.js:85:18)
    at eval (webpack-internal:///../../node_modules/.pnpm/@pkg.csb.dev+dnbexperience+eufemia+commit+89ea339f+@dnb@eufemia_@types+react-dom@18.2.25_@typ_u6l6ah63kdsofkxxrsacxiqmie/node_modules/@dnb/eufemia/extensions/forms/DataContext/Provider/Provider.js:490:65)
    at eval (webpack-internal:///../../node_modules/.pnpm/@pkg.csb.dev+dnbexperience+eufemia+commit+89ea339f+@dnb@eufemia_@types+react-dom@18.2.25_@typ_u6l6ah63kdsofkxxrsacxiqmie/node_modules/@dnb/eufemia/extensions/forms/hooks/useFieldProps.js:1204:105)
    at eval (webpack-internal:///../../node_modules/.pnpm/@pkg.csb.dev+dnbexperience+eufemia+commit+89ea339f+@dnb@eufemia_@types+react-dom@18.2.25_@typ_u6l6ah63kdsofkxxrsacxiqmie/node_modules/@dnb/eufemia/extensions/forms/hooks/useFieldProps.js:1258:13)
    at commitHookEffectListMount (webpack-internal:///../../node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:19590:42)
    at commitLayoutEffectOnFiber (webpack-internal:///../../node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:19691:37)
    at commitLayoutMountEffects_complete (webpack-internal:///../../node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:20844:25)
    at commitLayoutEffects_begin (webpack-internal:///../../node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:20833:21)
    at commitLayoutEffects (webpack-internal:///../../node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:20783:13)
    at commitRootImpl (webpack-internal:///../../node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:22572:17)
 ```

**Comment by andlbrei** [comment]
I have tried to figure out why I still get the null error locally, but not in CSB.
I tried comparing when debugging in CSB vs locally.
I figured out how it fails, and that the behaviour is different, but I don't know what it means/how to fix it.

What I found was that the fields within the `PushContainer` are set within the `updateDataValue` function in `Provider.js`.
In CSB the fields are only iterated over once. Locally they are iterated over twice.

The first run locally is equal to the only run in CSB and looks like this:
Note that `newData.newItems[0]` is an empty `Object`.
image

On the next pass `newData.newItems[0]` is `null`. This is when it fails.
image

**Comment by tujoworker** [comment]
yes, this was a tricky thing to get right. Now I think we are back on track. Can you test the latest version?

`https://pkg.csb.dev/dnbexperience/eufemia/commit/7b3bf06d/@dnb/eufemia`

**Comment by andlbrei** [comment]
No null error now 👏 

Still can't remove items.
Also noticed a new (?) problem:
Default value seems to stick.

In our project we toggle between user objects with certain data that is used as default data.
In the case of a new "blank" person the default data isn't set, but if a existing user is selected, and then we switch to new person the defaults are still present.

https://codesandbox.io/p/sandbox/iterate-defaultvalue-debug-dnthhd

**Comment by tujoworker** [comment]
Lets a have another round of testing 😄 The new version is `6b1f82fa`.

> Default value seems to stick.

The place where you use `defaultValue`, I would use just `value`. A defaultValue can not change, as it is only taken care of on the initial render (almost always, but not in the PushContaine, there it gets re-assigned after the fields have been cleaned).

**Comment by andlbrei** [comment]
Good point, `value` is the best choice there.
And it works.
But, it still sticks to fields even if they have no value or defaultValue defined if they share a path.
Dunno how important that is to "fix", it's a strange case.

Removing elements also works now 👍

**Comment by tujoworker** [comment]
I'm not sure how I can reproduce the sticking issue:

> But, it still sticks to fields even if they have no value or defaultValue defined if they share a path.

Let me know more about it. 

Can you check if that is an issue in this PR or if it is present in the latest version?

**Comment by andlbrei** [comment]
Seems like the issues have been solved now 👍

**Comment by andlbrei** [comment]
Seems like the issues have been solved now 👍

**Pull request merged**
