### PR TITLE
feat(Button): sbanken styling

### PR DESCRIPTION
**Pull request by snorrekim**
## Summary

The button component has been updated with the sbanken styling needed for now. Primary, secondary and tertiary button, as well as their large and icon button equivalents.

### CODE REVIEW

**Comment by tujoworker** [comment]
We have two conflicting files at the moment. Hope its OK for you if I rebase ✨

**Review by tujoworker — APPROVED** [review]
Looks good to me 👌 Nice work 🙏

We may look into excluding signal button examples when this PR #2280 is in.

**Review by langz — APPROVED** [review]
Looks great 👏 

@tujoworker, do we have a strategy in place for when a theme doesn't have a certain `variant`? Like removing the props from the prop list and/or removing the examples?
Reason for saying this is because it seems like the sbanken themed button don't have a "signal" variant:
image

**Comment by tujoworker** [comment]
@langz Yes, when PR #2280 is in, we can do that 👍

**Pull request merged**
