### PR TITLE
feat(Tag): add onDelete-prop

### PR DESCRIPTION
**Pull request by thaytharma**
Added `onDelete`-prop to `Tag`-component.

### CODE REVIEW

**Review by langz — APPROVED** [review]
I think it looks very nice 💯 

I have one comment that's not directly related to this:
I see that in a lot of our demos/examples we use `space={{right: 'x-small'}}`, etc. 
When not doing it, it seems to be a bit "crammed":
image

Should perhaps the tag group add some spacing as standard, and removing the spacing on the last item?
Might be that it's intentional to have this little space between the tags though, if so, then ignore my thoughts 👯

**Comment by andrewjrhill** [comment]
🤩   Looks great.

**Comment by thaytharma** [comment]
> I think it looks very nice 💯
> 
> I have one comment that's not directly related to this: I see that in a lot of our demos/examples we use `space={{right: 'x-small'}}`, etc. When not doing it, it seems to be a bit "crammed": image
> 
> Should perhaps the tag group add some spacing as standard, and removing the spacing on the last item? Might be that it's intentional to have this little space between the tags though, if so, then ignore my thoughts 👯

Great suggestion! Will have a discussion with the designers about the default group spacing etc.

**Pull request merged**
