### PR TITLE
docs(NumberFormat): fix info docs

### PR DESCRIPTION
**Pull request by langz**
From:
image

To:
image

### CODE REVIEW

**Comment by tujoworker** [comment]
ohh, do we use `pre` other places as well?

**Comment by langz** [comment]
> ohh, do we use `pre` other places as well?

I think so, there's a few references to `<pre` in different places.

**Review by tujoworker — APPROVED** [review]

**Comment by tujoworker** [comment]
It only effects when `pre` was used in .md files. So all other places should be fine from what I saw.

**Pull request merged**
