### PR TITLE
Update icon sizes for Button variant tertiary

### PR DESCRIPTION
**Pull request by dinarosv**
- Change icon size for button variant tertiary: 16px for left/right icons, 24px for top icons
- Fixed hover underline shift for tertiary button with icon top
- Made Content component in Button a functional component
- Moved Button propTypes (closer to a functional component)
- Had to fix close button in Global status, due to this change
- Updated screenshots, snapshots and Changelog

### CODE REVIEW

**Comment by dinarosv** [comment]
What is your thoughts on this PR, @tujoworker ?

**Review by OddKMS — APPROVED** [review]

**Comment by tujoworker** [comment]
Did you not see my review? Probably because its marked as pending? Have not been there before. I probably have to "submit" the review 😭

Screenshot 2021-11-20 at 07 15 36

**Comment by tujoworker** [comment]
We have to make a change here (probably revert the usage of margin vs top) because of multiline support. See the diff on this visual snapshot: https://github.com/dnbexperience/eufemia/pull/1142/commits/8e8b8ab19ac2e0bdcb6478f00c882c9af8ebbcc2?short_path=038f59d#diff-038f59dca22510a6030fa5d4879466b8538446842cdf1934c636bc746dfd37d6

**Comment by dinarosv** [comment]
aaah... no did not see your comment! 😞  Should I fix this now?

**Comment by tujoworker** [comment]
Yes, sounds good 🤩

**Pull request merged**
