### PR TITLE
feat(Breadcrumb): Added new component!

### PR DESCRIPTION
**Pull request by dinarosv**
- New component written with **React hooks** and **TypeScript**
- Tests written with **Testing Library**
- Version history:
  - Added variant single and multiple
  - Make storybook find .tsx stories, remove prettier config for .tsx
  - Added portal site for breadcrumb
  - Added variant collapse and handle translations
  - Updated sandbox with breadcrumb
  - Write tests and add screenshot tests
  - Updated documentation for Breadcrumb
  - Changes after Review (adding Section etc.)

### CODE REVIEW

**Comment by tujoworker** [comment]
Here's an [Codesandbox example](top="large"), using the PR version  👍

**Review by tujoworker — APPROVED** [review]
I very much like how it turned out! 🎉

For now, one last thing we need is to add `aria-expanded={isOpen}` on the open/close (collapse) button.

**Comment by langz** [comment]
Looking forward to use this feature 💯 👍

**Pull request merged**
