### PR TITLE
docs(Extension): convert md to mdx files

### PR DESCRIPTION
**Pull request by joakbjerk**

### CODE REVIEW

**Comment by tujoworker** [comment]
A small typo `docs:(Extension):` 👉 `docs(Extension):` in the PR title.

**Review by tujoworker — APPROVED** [review]
Looks good to me. Did you actually run it locally and check out the docs?

**Comment by joakbjerk** [comment]
> Looks good to me. Did you actually run it locally and check out the docs?

Yeah, I just did a check on all the docs pages and they seem to be working as intended locally :)

**Pull request merged**
