### PR TITLE
fix(InfoCard): issue on smaller screens

### PR DESCRIPTION
**Pull request by AadneRo**
### Summary

The component did not behave proparly on smaller screens, see screenshots for before and after visuals

### Before
Screenshot 2022-02-22 at 13 57 57

### After
Screenshot 2022-02-22 at 14 27 36

### CODE REVIEW

**Comment by thaytharma** [comment]
Looks good @AadneRo!

Just a minor nitpick:
Should the spacing be equal between text and buttons?

I guess this can be achieved by using margin-top on each of the buttons 🤔

Skjermbilde 2022-02-22 kl  14 37 44

**Comment by tujoworker** [comment]
Thank you @AadneRo 🙌

If you wish I can update the snapshots? I also see that there are just a few visual snapshots. Should we add more? or where there a reason that the attributes (`data-visual-test`) exists, but not the tests?

**Comment by AadneRo** [comment]
> Looks good @AadneRo!
> 
> Just a minor nitpick: Should the spacing be equal between text and buttons?
> 
> I guess this can be achieved by using margin-top on each of the buttons 🤔
> 
> Skjermbilde 2022-02-22 kl 14 37 44
> 
> EDIT: Btw, we also need to update the test files.

Thank you, it's done now

**Comment by AadneRo** [comment]
> Thank you @AadneRo 🙌
> 
> If you wish I can update the snapshots? I also see that there are just a few visual snapshots. Should we add more? or where there a reason that the attributes (`data-visual-test`) exists, but not the tests?

Updated the tests for this change, we can add more tests in a future PR

**Review by thaytharma — APPROVED** [review]
Nice work! 😍

**Pull request merged**
