### PR TITLE
chore(deps): update Gatsby to latest because of useful fix

### PR DESCRIPTION
**Pull request by tujoworker**
Because of this [fix](https://github.com/gatsbyjs/gatsby/pull/36623) which I think if have seen happening in our Portal as well.

Run lint with NODE_ENV=test in `lint:ci` to prevent babel parsing error (because of babel config change it gets picket up now)

### CODE REVIEW

**Review by langz — CHANGES_REQUESTED** [review]
I gave it a `yarn reset`, and a `yarn start`.
This is what happens locally here when I visit http://localhost:8000/:
image

Could of course just be something with my computer setup 🤔

**Comment by tujoworker** [comment]
> This is what happens locally here when I visit

Renaming the babel config file the how its state in the [documentation](https://www.gatsbyjs.com/docs/how-to/custom-configuration/babel/#how-to-use-a-custom-babelrc-file) (`babel.config.cjs` => `.babelrc`) seems to help.

**Review by langz — COMMENTED** [review]
This time around, I did the same:`yarn reset`, and a `yarn start`.
This is what happens locally here when I visit http://localhost:8000/:

https://user-images.githubusercontent.com/1359205/194820626-01d05805-dc4d-4f1d-ae17-4e5f917b59b1.mov

**Comment by tujoworker** [comment]
aww, this time also the CI suffers with the same result as you got. Anyway, it looks like it works fine now. At least for me when I run the same reset command as you did.

**Comment by tujoworker** [comment]
no does not work properly yet, I will have to come with an update.

**Comment by tujoworker** [comment]
Now it should work properly. There where some small changes in the internal Webpack config from Gatsby. So made an additional commit.

**Review by langz — APPROVED** [review]
Thanks, looks and works great locally now :)

**Comment by tujoworker** [comment]
We may rather rebase this PR once #1623 has landed.

**Pull request merged**
