### PR TITLE
fix(Forms): should display error underneath fields when nested inside Field.Selection or Field.ArraySelection  

### PR DESCRIPTION
**Pull request by langz**
As of now, this PR just adds an example of what should be fixed/improved upon.

Here's a link to the example in the [deploy preview](https://eufemia-git-chore-add-selection-example-eufemia.vercel.app/uilib/extensions/forms/base-fields/Selection/demos/#radio-nesting-advanced), and here [locally](http://localhost:8000/uilib/extensions/forms/base-fields/Selection/demos/#radio-nesting-advanced).

The challenge/problem is that error messages for fields nested inside an `Field.Selection` is not displayed underneath each respective field, but rather merged and displayed at the bottom of the `Field.Selection`, like so:

image

### CODE REVIEW

**Comment by tujoworker** [comment]
I'm not sure if it is meaningful to include the advanced use-case, as the other is very similar. But as of now, we have it. We also keep it "open" by default, so you don't need to click around to see the nested fields:

https://eufemia-git-chore-add-selection-example-eufemia.vercel.app/uilib/extensions/forms/base-fields/Selection/demos/#radio-nesting-advanced

**Comment by langz** [comment]
> I'm not sure if it is meaningful to include the advanced use-case, as the other is very similar. But as of now, we have it. We also keep it "open" by default, so you don't need to click around to see the nested fields:
> 
> https://eufemia-git-chore-add-selection-example-eufemia.vercel.app/uilib/extensions/forms/base-fields/Selection/demos/#radio-nesting-advanced

Thanks, I'll use it for testing purposes for now at least.
Perhaps we just remove it before merging

**Comment by langz** [comment]
Great work @tujoworker, works excellent ❤️ 
I'm fine with removing the example, as it's just a complicated example, but could be nice to move it to a story or so, as it's very helpful to test the features. Perhaps rename example "Radio nesting advanced" to story "Field.Selection deep nesting" or so.

**Comment by tujoworker** [comment]
We need to rebase this PR and update the visual snapshots, after PR #4244 has been merged.

**Comment by langz** [comment]
> We need to rebase this PR and update the visual snapshots, after PR #4244 has been merged.

Done 🥇

**Comment by langz** [comment]
> > We need to rebase this PR and update the visual snapshots, after PR #4244 has been merged.
> 
> Done 🥇

Once more 😓

**Pull request merged**
