### PR TITLE
chore(Storybook): move stories in their source directories

### PR DESCRIPTION
**Pull request by tujoworker**
This PR is all about moving all Storybook files into their component source folders. We also rename the files to include `.stories` in the filename:

`.../storybook-package/components/Button.tsx`
👇
`dnb-eufemia/src/components/button/stories/Button.stories.tsx`

With this, stories are quicker to find and interact with – and we also type check types  + lint (ESLint) on the CI.

### CODE REVIEW

**Comment by tujoworker** [comment]
I will squash all commits before/during pr merge 👍

**Review by dinarosv — APPROVED** [review]
Really good work! Also nice that you updated the docs for this 🙌

**Pull request merged**
