### PR TITLE
feat(Forms): add `{nextItemNo}` support to Iterate.PushButton

### PR DESCRIPTION
**Pull request by tujoworker**
Quick example:

```tsx
<Form.Handler>
  <Iterate.Array path="/myList">
    <Field.String itemPath="/" />
  </Iterate.Array>

  <Iterate.PushButton
    path="/myList"
    pushValue="push value"
    text="Add no. {nextItemNo}"
  />
</Form.Handler>,
```

### CODE REVIEW

**Review by langz — APPROVED** [review]
Looks good, it probably makes sense that the propname is itemNr even though it displays the itemNr for the next item? 
Is that how the itemNr works elsewhere as well?

Just don't want out consumers to be confused about an itemNr here and one there, and why it does not display the same value...

**Comment by tujoworker** [comment]
Agree, I had nextItemNr before committing as well. 
It can never be prevItemNr. 
So maybe it will be more declarative to name it nextItemNr.

Just a small detail; Should we name it "No" instead of "Nr"? "No" is actually the more correct term in English. So we can start with the new one and change the others incrementally.

**Comment by langz** [comment]
> Agree, I had nextItemNr before committing as well. 
> It can never be prevItemNr. 
> So maybe it will be more declarative to name it nextItemNr.
> 
> Just a small detail; Should we name it "No" instead of "Nr"? "No" is actually the more correct term in English. So we can start with the new one and change the others incrementally. 
> 

Sounds smart, I agree 🫡

**Review by langz — APPROVED** [review]

**Pull request merged**
