### PR TITLE
feat(forms): Session storage on Provider and add defaultData prop

### PR DESCRIPTION
**Pull request by henit**

### CODE REVIEW

**Review by tujoworker — CHANGES_REQUESTED** [review]
Nice work so far 👌 would be awesome to have a test coverage for the new prop  / the changes.

I also think about, if its clear enough for a dev to know whats happening, when reading the code and seeing the prop `sessionId` 🤔

**Comment by henit** [comment]
> I also think about, if its clear enough for a dev to know whats happening, when reading the code and seeing the prop `sessionId` 🤔

Do you think the prop should be renamed, or more clearly explained in the documentation?

**Comment by tujoworker** [comment]
Yes, if we name the prop e.g. `sessionStorageId` it helps. Maybe even `storageId`.

**Comment by henit** [comment]
> Yes, if we name the prop e.g. `sessionStorageId` it helps. Maybe even `storageId`.
> 
> Does the store get reset on submit by default? or should we provide a "clean/reset" function in a hook?

I don't know if it will happen, but in case the component would end up supporting multiple ways of storage at some point (like local storage, indexed db, service worker mechanism or some common server side API), maybe we should include the word "session"? AKA: Supporting the suggestion of `sessionStorageId`

**Pull request merged**
