### PR TITLE
fix(Anchor): fix Link class no-underline when used in DNB Section

### LINKED ISSUE #1505: The dnb-anchor--no-underline class does not work as expected with emerald-green style_type on sections.
## 🐛 Bug Report

The dnb-anchor--no-underline class does not work as expected with emerald-green style_type on sections. 
## To Reproduce

```
    <Section spacing  style_type="emerald-green">
            <Link
              className={"dnb-anchor--no-underline"}
              to={"google.com"}
            >
              google.com
            </Link>
    </Section>
```
https://codesandbox.io/embed/romantic-dirac-w8bspd?fontsize=14&hidenavigation=1&theme=dark

## Expected behavior

The above code should show links without underlines but it shows links with underlines. same issue is with dnb-anchor--no-style class. This is probably because of this code https://github.com/dnbexperience/eufemia/blob/main/packages/dnb-eufemia/src/components/section/style/themes/dnb-section-theme-ui.scss#L99

## Eufemia Version

9.27.0

The isse can be seen on https://developer.dnb.no/    footer section
Screenshot 2022-08-12 at 01 12 20

### PR DESCRIPTION
**Pull request by tujoworker**
Fixes #1505

Relies on #1508 to successfully run the failing visual test

### CODE REVIEW

**Review by langz — APPROVED** [review]

**Review by langz — APPROVED** [review]
Nice nice :)
Love the screenshot test, shows that the bug/issue is fixed 🥇

**Comment by chetanDhanvij** [comment]
@langz @tujoworker,

Can this be merged now :)

**Comment by tujoworker** [comment]
Yes, just did a rebase from main and the tests are now successful.

**Pull request merged**
