### PR TITLE
fix(Slider): enhance Safari (desktop) UX

### PR DESCRIPTION
**Pull request by tujoworker**
- Enhance "animate to" implementation
- Ensure pointer cursor is shown during dragging on Safari (desktop)

Slider [demos of this build](https://eufemia-fixsafariux.gtsb.io/uilib/components/slider/demos/).

### CODE REVIEW

**Comment by langz** [comment]
When testing this on my iPhone in both Chrome and Safari, I'm now not able to drag/slide the slider.
See video below:

https://user-images.githubusercontent.com/1359205/187670902-65f740eb-7997-440a-9a1b-66123267cbe2.mov

**Review by langz — CHANGES_REQUESTED** [review]
When testing this on my iPhone in both Chrome and Safari, I'm now not able to drag/slide the slider anymore.
See video below:

https://user-images.githubusercontent.com/1359205/187670902-65f740eb-7997-440a-9a1b-66123267cbe2.mov

**Comment by tujoworker** [comment]
> I'm now not able to drag/slide the slider anymore.

Going forward with the old implementation, where the "track" has the "starting" event handler. We still achieve our two goals, mentioned in the PR description.

**Review by langz — APPROVED** [review]

**Pull request merged**
