### PR TITLE
fix(Icons): prevent icons from having same IDs (duplicate-id violation)

### PR DESCRIPTION
**Pull request by tujoworker**
Thanks for @dinarosv for reporting 🙏

After the change, SVG IDs get the file-name, so they will be unique per icon. But not per page. So that's still an issue. And can lower a lighthouse score, still.

IDs in SVGs are used in order to link the usage of `clipPath`.

Its the Figma export that sets this. 52 icons are effected (from a total of 260).

E.g. the `thumb_up` (16px) uses this, but not `thumb_up` (24px) – I'm not sure why this difference. We may try to find out more about it.

Approaches we can do to enhance this beyond this PR:

- find out more about, why Figma uses `clipPath` on some icons, and sddenly not on very similar icons.
- generate an unique ID during React render. Not streight forward to make it work. 
- remove all usage of `clipPath`. What are the side-effects? They can be different from icon to icon.
- try to find a way to transform the `clipPath` usage. But that's not so easy. There is an [open issue/request](https://github.com/svg/svgo/issues/680) for it.

In this PR, we get this change:

Screenshot 2022-11-10 at 08 53 31

Screenshot 2022-11-10 at 08 52 43

### CODE REVIEW

**Review by dinarosv — APPROVED** [review]
Thanks for the super quick fix 🙌

**Review by langz — APPROVED** [review]
✅

**Comment by buzinas** [comment]
Just so y'all know, Figma exports `clipPath` when "Clip content" is checked:

image

In the majority of cases, you don't need to clip any content. So if you uncheck it, there are no visual changes, but the exported SVG doesn't have this `clipPath` garbage:

Before | After
-- | --
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 16 16" fill="currentColor"><defs><path id="export-a" d="M12.4545455,14.125 L13.7272727,14.125 L13.7272727,13.5 L12.4545455,13.5 L12.4545455,14.125 Z M15,16 L1,16 L1,12.875 C1,12.53125 1.28636364,12.25 1.63636364,12.25 L14.3636364,12.25 C14.7136364,12.25 15,12.53125 15,12.875 L15,16 Z M6.09090909,1.625 C6.09090909,1.28125 6.37727273,1 6.72727273,1 L9.27272727,1 C9.62272727,1 9.90909091,1.28125 9.90909091,1.625 L9.90909091,6 L13.0209091,6 C13.3709091,6 13.4663636,6.20875 13.2321818,6.465 L8.36018182,11.785 C8.126,12.04125 7.74418182,12.04 7.51127273,11.7825 L2.69527273,6.4675 C2.46363636,6.21 2.55909091,6 2.90909091,6 L6.09090909,6 L6.09090909,1.625 Z"/></defs><use fill-rule="evenodd" xlink:href="#export-a"/></svg>` | `<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12.4545 14.125H13.7273V13.5H12.4545V14.125ZM15 16H1V12.875C1 12.5312 1.28636 12.25 1.63636 12.25H14.3636C14.7136 12.25 15 12.5312 15 12.875V16ZM6.09091 1.625C6.09091 1.28125 6.37727 1 6.72727 1H9.27273C9.62273 1 9.90909 1.28125 9.90909 1.625V6H13.0209C13.3709 6 13.4664 6.20875 13.2322 6.465L8.36018 11.785C8.126 12.0412 7.74418 12.04 7.51127 11.7825L2.69527 6.4675C2.46364 6.21 2.55909 6 2.90909 6H6.09091V1.625Z" fill="currentColor" /></svg>`

**Comment by ivanbanov** [comment]
thanks for pointing out @buzinas ❤️

**Pull request merged**
