### PR TITLE
docs(Paragraph): move docs from /typography to /elements

### PR DESCRIPTION
**Pull request by langz**
Moved Paragraph docs from /typography to /elements.
I've not adjusted any of the contents of the docs yet, could be worth revising this now that it's been moved.

### CODE REVIEW

**Comment by langz** [comment]
Hmm, not exactly sure how I can make it stop looking for the nonexistent `Docs/uilib/typography/Examples`
https://github.com/dnbexperience/eufemia/actions/runs/3471385542/jobs/5800806330#step:8:61

**Review by tujoworker — APPROVED** [review]
Nice! I pushed a [commit](https://github.com/dnbexperience/eufemia/pull/1727/commits/b47392dcc654962bef886d814ef6c8ca5f7652a0) as well 👍

**Comment by langz** [comment]
> Nice! I pushed a [commit](https://github.com/dnbexperience/eufemia/pull/1727/commits/b47392dcc654962bef886d814ef6c8ca5f7652a0) as well 👍

Great, thanks :)

**Pull request merged**
