### PR TITLE
chore(Field.Date): wrap in FieldBlock

### PR DESCRIPTION
**Pull request by tujoworker**
Relies on #3188 and will be rebased once it is in main: ✅

### CODE REVIEW

**Review by joakbjerk — COMMENTED** [review]
Should we perhaps set a default width so the component is not so wide out of the box?
Screenshot 2024-01-08 at 14 39 21

and the error styling seems to not be applied anymore
Screenshot 2024-01-08 at 14 40 52

**Comment by tujoworker** [comment]
Yes! Nice you check the actual outcome 🥇 – I've added two visual tests now ✅ 
Also, we do not handle width, as we are better with the given width. Also for future compatibility for date-range support.

**Review by joakbjerk — APPROVED** [review]
Great, looks perfect now! 🔥

**Pull request merged**
