### PR TITLE
chore(Block.ChildrenWithAge): improves the animation

### PR DESCRIPTION
**Pull request by langz**

### CODE REVIEW

**Comment by langz** [comment]
I have to make a few minor improvements here, as the screenshot test is actually reporting a problem with my code.

**Review by tujoworker — APPROVED** [review]
There's more white space now, but that's intended?

Screenshot 2024-10-18 at 11 23 00

**Comment by langz** [comment]
> I have to make a few minor improvements here, as the screenshot test is actually reporting a problem with my code.



> There's more white space now, but that's intended?
> 
> Screenshot 2024-10-18 at 11 23 00

https://github.com/dnbexperience/eufemia/pull/4148#issuecomment-2421949924

No, I'll look into it before merging 🏁

**Pull request merged**
