### PR TITLE
chore(Typography): create visual tests for all typography theming

### PR DESCRIPTION
**Pull request by joakbjerk**

### CODE REVIEW

**Review by tujoworker — APPROVED** [review]
It looks good to me. Even, I think, Eiendom has no changes to paragraph styles. So I would argue;

> we should not test what we don't change. 

Just because it creates parts we need to maintain in future.

**Review by langz — APPROVED** [review]

**Comment by tujoworker** [comment]
The snyk CI seems to be hanging. Should I merge it, or do you want to re-run the CI?

**Comment by joakbjerk** [comment]
> The snyk CI seems to be hanging. Should I merge it, or do you want to re-run the CI?
 
You can merge it if you want 🙏

**Pull request merged**
