### PR TITLE
chore: make Portal windows compatible by properly handle backslashes and newlines

### PR DESCRIPTION
**Pull request by tujoworker**
It needs to be tested on a Windows PC:

1. git fetch
1. git switch chore/portal-windows-support
1. yarn clean && yarn start

### CODE REVIEW

**Review by langz — APPROVED** [review]
This PR runs great on my machine, MacBook Pro, how about on your Windows machine @eliland?

**Comment by tujoworker** [comment]
> This PR runs great on my machine, MacBook Pro, how about on your Windows machine @eliland?
> 
> 

I had a session with him and withe the extra commit, it worked fine 🙌

**Review by eliland — APPROVED** [review]
Works flawlessly from Windows now!

**Pull request merged**
