### PR TITLE
docs: fix spelling, typos & grammar

### PR DESCRIPTION
**Pull request by thaytharma**
Fixed some spellings, typos & overall grammar in the docs. Most of them are minor changes.

A lot of the "mistakes" are copied from one file to another, 
so changing them would be beneficial for all maintainers and Eufemia users.

### CODE REVIEW

**Review by dinarosv — APPROVED** [review]
Wow! Thank you so much for this 😍 

Did you go over all manually or do you have a nice program for it? I would like to have that too! 😄

**Comment by tujoworker** [comment]
@thaytharma Incredible work 👍 💯 

You can squash all three commits into one when merging this PR with squash 👍

Screenshot 2021-12-15 at 15 29 09

**Review by tujoworker — APPROVED** [review]

**Comment by thaytharma** [comment]
> Also, could you squash your commits to 1 before merging? We try to have a clean git-tree, but I'm not 100% perfect there either 😄

Done! Thanks @tujoworker

**Comment by thaytharma** [comment]
> Wow! Thank you so much for this 😍
> 
> Did you go over all manually or do you have a nice program for it? I would like to have that too! 😄

Used Grammarly! Very helpful!

**Pull request merged**
