### PR TITLE
fix(Breadcrumb): Pass rest props to item when not interactive

### PR DESCRIPTION
**Pull request by langz**
I believe/hope this should fix the reported issue here: https://github.com/dnbexperience/eufemia/pull/2676/files#r1368576095

### CODE REVIEW

**Review by thaytharma — APPROVED** [review]
Thanks 😍

**Review by tujoworker — APPROVED** [review]
Nice! And nice tests as well! Sounds also that you not found any issues forwarding such props to the span 🎉

**Comment by langz** [comment]
> Nice! And nice tests as well! Sounds also that you not found any issues forwarding such props to the span 🎉

I've not looked extensively at this, is there a greater risk of passing props to the span now, than before https://github.com/dnbexperience/eufemia/pull/2676/files#r1368576095?

Maybe we should "filter out" the "button props" to not getting drilled down to the `span`?

I can take a look tomorrow in our storybook and test the consequences of passing down all button props to the span, and see what happens 🙏

**Comment by tujoworker** [comment]
We may add the filterProps addition #2802 – I have a commit ready locally and can push it after a rebase.

**Comment by langz** [comment]
Perfect, thanks!
I’ll continue with this after todays morning meetings

**Comment by langz** [comment]
Maybe we should add a comment, or add this PR to a list of things we probably can remove in the next breaking change/release?
Reason being, is because I'm not sure if this feature is really needed, or if it's just to be able to pass down `data-testid`'s.

I think it's fair that we now add it back to a v10 release for now, as we introduced sort of a "breaking change" by removing this in https://github.com/dnbexperience/eufemia/pull/2676/files#r1368576095 as part of a minor release. But in v11, maybe it's okay to remove it, and document it, as I think it's only used for passing down `data-testid`'s for now, which maybe is not a good enough reason to have it? 🤔

**Comment by tujoworker** [comment]
Yes, I agree.

**Comment by langz** [comment]
I've added a few commits
- https://github.com/dnbexperience/eufemia/pull/2798/commits/98f7d472a45460af4020c79ed5e75c322d2aa3be
- https://github.com/dnbexperience/eufemia/pull/2798/commits/0e119b365a5197adc4bdfc963a2fcab2e4ed3abd
- https://github.com/dnbexperience/eufemia/pull/2798/commits/8220d5dab333b806b91da901f661db9d788d1e50

And believe this should be good to go now 🙏

**Pull request merged**
