### PR TITLE
chore: use css variables in utility breakpoints

### PR DESCRIPTION
**Pull request by thaytharma**
Used  CSS- variables in utility breakpoints instead of hardcoded values.

### CODE REVIEW

**Comment by thaytharma** [comment]
The tests are failing.. I mean, that makes sense 😂

**Comment by tujoworker** [comment]
It’s not possible to use “var” in media queries as of now.

**Comment by thaytharma** [comment]
> It’s not possible to use “var” in media queries as of now.

Yes, I'll decline and delete the PR 😊

**Comment by thaytharma** [comment]
https://github.com/dnbexperience/eufemia/pull/1242#issuecomment-1028079172

**Pull request closed without merging**
