### PR TITLE
fix(Visibility): add support for being used in Flex.Container

### PR DESCRIPTION
**Pull request by tujoworker**
Thank you @kimroen for the [CSB](https://codesandbox.io/p/sandbox/laughing-bash-f2d5zm) reprod. 👌

### CODE REVIEW

**Review by joakbjerk — APPROVED** [review]
Nice, looks as intended now 😄

**Comment by tujoworker** [comment]
Here is a [reprod](https://codesandbox.io/p/sandbox/frosty-cookies-vflmkd?file=%2Fpackage.json%3A6%2C39) with the fixed version.

**Comment by kimroen** [comment]
> Here is a [reprod](https://codesandbox.io/p/sandbox/frosty-cookies-vflmkd?file=%2Fpackage.json%3A6%2C39) with the fixed version.

Glorious! 🙌

**Pull request merged**
